### ISSUE TITLE
Proposal: Move wording in to Rails's i18n dictionary

### ISSUE THREAD

**Issue by cyril** [etalab/admin_api_entreprise#102]
To organize the information well, this issue proposes to no longer mix the code and the texts together.

To achieve this, using Rails i18n seems to be the most standard solution.

Even if today only one language is supported (Cocorico 🇫🇷), having a dictionary of translations should make it easier to read and contribute to the code, by removing strings sometimes over several lines.

**Comment by brindu** [comment]
As we quickly discussed already there is not going to be another language anytime soon.

So imo there is no need to add an i18n layer for just a single language.

**Comment by cyril** [comment]
The fact that we only have one language does not prevent us from being able to take advantage of the functionalities offered by [i18n](https://guides.rubyonrails.org/i18n.html). This tool is already included in the framework, so why not use it?

The logic specific to wording has its peculiarities, and i18n gives us some automatic features to deal with them like:
- pluralization
- integration with Rails helpers (example: `distance_of_time_in_words`)
- default translations
- the translation of fields, models, email subjects, etc.

I18n offers us these features to simplify the integration work and not have to reinvent the wheel with some custom code mixed up in [models](https://github.com/etalab/admin_api_entreprise/blob/03b15e0059b70adfbf01ca520cb6f9caf9aa7d1d/app/models/jwt_api_entreprise.rb#L14-L16), [controllers](https://github.com/etalab/admin_api_entreprise/blob/03b15e0059b70adfbf01ca520cb6f9caf9aa7d1d/app/controllers/oauth_api_gouv_controller.rb#L13-L22), [mailers](https://github.com/etalab/admin_api_entreprise/blob/03b15e0059b70adfbf01ca520cb6f9caf9aa7d1d/app/mailers/user_mailer.rb#L14) and other unusual places.

Thus, potential contributors can more easily come and contribute. They instantly know that the French wording will be in `fr.yml`. Rails offers conventions and best practices for everyone, even for applications in French.

And later if we have to add some other languages (and we probably will have to), it will cost less to deal without the big bang effect. There is no small debt.

**Comment by skelz0r** [comment]
I think it's not a priority too.

> And later if we have to add some other languages (and we probably will have to), it will cost less to deal without the big bang effect. There is no small debt.

> (and we probably will have to)

I don't think so, not in short/middle term

> it will cost less to deal without the big bang effect. There is no small debt.

With the minimal amount of wordings, it'll be pretty easy to migrate wordings. There's currently no real reason to add i18n, it's, in my opinion, a premature optimisation which can lead to a more complexity (we will have to check if our keys are correctly used, without translation missing, which will leads to more test to maintain), where it's not a real enhancement : with this point of view, adding i18n is a debt.
