### ISSUE TITLE
Notification Datapass de changement de propriétaire incomplète

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#1048]
Dans le mail qu'on envoie à Datapass on est sensé envoyer la liste des Datapass à transférer. Apparemment ça n'est pas le cas cf ce ticket de support : https://support.etalab.gouv.fr/#ticket/zoom/59336

La récupération se fait ici : 
https://github.com/etalab/admin_api_entreprise/blob/04329ca218b48ca343212751686b956df4b3456a/app/mailers/user_mailer.rb#L27

Je suspecte que les Datapass ait déjà été transférés à ce moment du code. Le quick dev (un peu dégueux) serait de récupérer les Datapass de l'ancien email et du nouveau pour être sûr de tout avoir... mais c'est aussi ne pas chercher où est le problème 😅

**Comment by Samuelfaure** [comment]
Ceci vient très probablement du bug https://github.com/etalab/admin_api_entreprise/issues/1038

Je ferme
