### ISSUE TITLE
Supprimer "Admin" definitivement

### ISSUE THREAD

**Issue by Samuelfaure** [etalab/admin_api_entreprise#1053]
Colonne présente sur les users, ignorée explicitement dans le modèle.

A supprimer.

Avant ça, supprimer en prod les users avec admin = true

**Comment by skelz0r** [comment]
> Avant ça, supprimer en prod les users avec admin = true

Honnêtement on s'en fiche ici imo.

Sinon oui let's do this.

**Comment by Samuelfaure** [comment]
J'ai supprimé quelques comptes "admin" d'anciens collègues.

En dehors de ça t'as raison, pas besoin de se faire ièche à supprimer ces comptes j'imagine.

**Comment by Samuelfaure** [comment]
Finition dans cette PR https://github.com/etalab/admin_api_entreprise/pull/1062
