### ISSUE TITLE
Uniformiser les organizers de login

### ISSUE THREAD

**Issue by Samuelfaure** [etalab/admin_api_entreprise#1063]
Organizer login API Entreprise:

```ruby
class APIEntreprise::User::OAuthLogin < ApplicationOrganizer
  organize User::FindFromEmail,
    User::UpdateOAuthAPIGouvId,
    User::NotifyDatapassOfTokenOwnership
end
```

Organizer login API Particulier:

```ruby
class APIParticulier::User::OAuthLogin < ApplicationOrganizer
  organize User::FindFromEmail,
    User::UpdateOAuthAPIGouvId
end
```

On veut probablement le même comportement aux deux endroits, pas de raison de ne pas notifier Datapass dans un cas mais pas dans l'autre? => Utiliser un organizer unique dans les deux cas, ça sera + propre

**Comment by skelz0r** [comment]
> On veut probablement le même comportement aux deux endroits

Non. Il n'y a pas de transfert de jetons sur API Particulier si je ne m'abuse.
