### ISSUE TITLE
Problème d'UX connexion

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#1085]
Certains utilisateurs (cf support), ont tenté d'accéder à API Entreprise en se créant simplement un compte sur MonComptePro, sans faire de demande Datapass...

- https://support.etalab.gouv.fr/#ticket/zoom/60591
- https://support.etalab.gouv.fr/#ticket/zoom/60590

Points d'attentions : 
- dans l'idéal il ne faudrait pas que MonComptePro propose la création de compte ; qu'on redirige vers un module uniquement de connexion
- en attendant je propose de patcher en ajoutant un message et un lien vers le formulaire api.gouv.fr

P.S: issue d'origine sur le mauvais repo : https://github.com/etalab/siade/issues/802

**Comment by Haelle** [comment]
> dans l'idéal il ne faudrait pas que MonComptePro propose la création de compte ; qu'on redirige vers un module uniquement de connexion
> ???
 
Qu'on renvoie les gens vers une page MonComptePro qui ne permette pas de créer un compte, juste de login sans lien vers une page de création de compte. Aujourd'hui ça détecte tout seul si t'as un compte ou non.
 
> Ici le problème est surtout qu'on devrait suivre l'UX classique d'une connexion en OAuth: créer un compte shrug
 
Compte shrug ?
 
> PS: Ce n'est pas le bon dépôt, je t'invite à le transférer.
 
Mince :/, mais je ne peux pas transférer d'un repo privé à un repo public (l'inverse oui par contre), c'est dans la doc Github, c'est pour éviter de leak des trucs confidentiels

**Comment by skelz0r** [comment]
Pour moi il faut que n'importe quelle connexion valide via MCP trouve ou crée un compte chez nous.

Si c'est un nouvel utilisateur, son tableau de bord est vide et on a le champ libre pour gérer l'UX, ce qui résoud immédiatement les 2 tickets.

**Comment by skelz0r** [comment]
> > Ici le problème est surtout qu'on devrait suivre l'UX classique d'une connexion en OAuth: créer un compte shrug
> 
> Compte shrug ?

Je pense que ton navigateur ou OS ne traduit pas l'emoji shrug, en gros je disais "créer un compte"

**Comment by skelz0r** [comment]
> Niveau homologation de sécurité c'est considéré comme un vecteur d'attaque, une fois connecté t'as plus de droits et peux tenter des opérations d'élévations de privilèges plus facilement.

Je suis désolé mais c'est une justification bidon .. C'est déjà un vecteur d'attaque en l'état. D'autant plus que la seule façon de créer un jeton c'est via les webhooks DataPass, ce qui est complètement décorellé de la gestion des comptes utilisateurs. 

Si tu veux faire kiss on peut mettre un message d'erreur explicite, mais c'est une opportunité manquée.

--------

<img width="996" alt="Screenshot 2023-06-13 at 11 36 36" src="https://github.com/etalab/admin_api_entreprise/assets/1279968/18d9d488-47bf-435e-89db-96821a8532d5">

Pour le shrug --^

**Comment by Haelle** [comment]
> > Niveau homologation de sécurité c'est considéré comme un vecteur d'attaque, une fois connecté t'as plus de droits et peux tenter des opérations d'élévations de privilèges plus facilement.
> 
> Je suis désolé mais c'est une justification bidon .. C'est déjà un vecteur d'attaque en l'état. 

Ça donne plus d'importance aux tests d'intrusions auxquels je n'ai absolument pas confiance car il n'y en a même pas eu... 
Mais oui, c'est un peu bidon, mais si on peut je préférerai éviter une exposition supplémentaire des jetons si on peut l'éviter.
Personne n'a fait de tests d'intrusions et on a pas d'experts en sécu.

> D'autant plus que la seule façon de créer un jeton c'est via les webhooks DataPass, ce qui est complètement décorellé de la gestion des comptes utilisateurs.

Ici je parle d'élévation de privilège, si on a une faille de sécurité qui permette à un usager de voir un autre jeton, le fait d'avoir un jeton de session rend plus facile une attaque.
Il existe notamment des failles qui se base sur un Cookie connu pour tenter d'en générer d'autres valides, qui nécessitent de d'avoir un ou plusieurs cookie d'exemple de l'app (même des cookie expirés).

> Pour le shrug --^

Indeed, c'est Mac ça !

**Comment by skelz0r** [comment]
> > D'autant plus que la seule façon de créer un jeton c'est via les webhooks DataPass, ce qui est complètement décorellé de la gestion des comptes utilisateurs.
> 
> Ici je parle d'élévation de privilège, si on a une faille de sécurité qui permette à un usager de voir un autre jeton, le fait d'avoir un jeton de session rend plus facile une attaque. Il existe notamment des failles qui se base sur un Cookie connu pour tenter d'en générer d'autres valides, qui nécessitent de d'avoir un ou plusieurs cookie d'exemple de l'app (même des cookie expirés). Donc éviter de donner un jeton à un attaquant c'est pas plus mal.

Par design chaque internaute venant sur le site possède un cookie de session. 

ici dtf il y a tellement des moyens 100x plus simple et obvious de récupérer un jeton d'un user que c'est vraiment tiré par les cheveux les justifications ici. D'ailleurs j'avais proposé de limiter / IP / jeton ( [ici](https://github.com/etalab/admin_api_entreprise/issues/952#issuecomment-1567169702) ).

Go affiner le message d'erreur chez nous et move on imo.

**Comment by skelz0r** [comment]
hop() https://github.com/etalab/admin_api_entreprise/pull/1086
