### ISSUE TITLE
Jeter la table scope

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#1104]
s'assurer qu'il n'y a pas d'impact, mais comme la classe derrière n'existe même plus je pense qu'on est serein 

Tables à jeter :
- `scopes`
- `scopes_tokens`

**Comment by skelz0r** [comment]
Alors `scopes` c'est TRES étrange qu'elle soit encore présente car aa2aa7986098f65d5dca8884ec32e97bcfe432f6 était censé l'avoir drop, je suis un peu confus.

Faudrait aller creuser voir pourquoi ce n'est pas le cas.

Au passage y'a moyen que ça fasse sauter des questions metabase.

**Comment by skelz0r** [comment]
(mais `scope_tokens` oui c'est un oubli)
