### ISSUE TITLE
Proposal: Use dotenv

### ISSUE THREAD

**Issue by cyril** [etalab/admin_api_entreprise#112]
In test and development environments, we could add those files:

* `.env.development.local.example`: versioned, includes ALL obfuscated keys
* `.env.development.local`: not versioned, includes ALL keys
* `.env.test.local`: versioned, includes ALL obfuscated keys

**Comment by brindu** [comment]
Il y a au moins les credentials à l'oauth API Gouv (leur staging) dans les fichiers de dev donc : 
* soit on l'encrypte, et les credentials de Rails sont là pour ça 
* soit on fait comme tu proposes et il faut aller chercher ce secret dans le Ansible tout comme on va chercher la clé master aujourd'hui. 

Je ne vois aucun gain à cette proposition.

**Comment by cyril** [comment]
👍

**Comment by skelz0r** [comment]
> Je ne vois aucun gain à cette proposition.

J'en vois un pour le coup -> tu explicites clairement dans `.env.development.local.example` les clés nécessaire à la config, ce qui te permet de dev en isolation sans avoir à aller chercher une quelconque valeur de prod. En l'état tu ne peux pas pleinement dev/faire tourner le projet sans récupérer les infos depuis ansible, ce qui n'est pas ouf (aucun contributeur externe ne peut travailler sur ce repo).

Après de là à migrer la stack c'est une autre histoire, mais si on peut utiliser `.env.ENV.local.example` avec la stack credentials de rails, pourquoi s'en priver ?

**Comment by cyril** [comment]
D'accord avec toi. Que dirais-tu d'ajouter un fichier `config/credentials/development.yml.example` pour ça ?

Autre sujet,

~Je pense que ce serait bien de déplacer `config/credentials.yml.enc` vers `config/credentials/development.yml.enc` (et `config/master.key` vers `config/credentials/development.key`) pour explicitement montrer qu'il s'agit des paramètres de l'environnement de développement.~

Ça pourrait être une bonne chose d'ignorer du versionnement le fichier des credentials de développement. Chaque développeur pourrait avoir ses propres comptes de test, pour pouvoir par exemple jouer avec des services distants en tout indépendance sans side-effects avec ce que font les autres développeurs eux aussi. C'est notamment ce qui distingue l'environnement de développement et l'environnement staging (sur lequel à l'inverse tous les crédentials sont prédéterminés, tout comme le jeu de données en DB).

Et pour l'environnement de test, je sais pas si vous avez des idées, moi je crois qu'une solution serait de juste mocker les valeurs des paramètres issus de l'environnement. Un peu comme ici : https://github.com/rspec/rspec-rails/issues/2099.

**Comment by skelz0r** [comment]
Si je comprends bien finalement tu proposes de repasser sur un fichier de config ?

Au passage, je sais pas quand ça a été introduit mais dans le help de credentials (`rails credentials:help`)

```
=== Environment Specific Credentials

The `credentials` command supports passing an `--environment` option to create an
environment specific override. That override will take precedence over the
global `config/credentials.yml.enc` file when running in that environment. So:

   bin/rails credentials:edit --environment development

will create `config/credentials/development.yml.enc` with the corresponding
encryption key in `config/credentials/development.key` if the credentials file
doesn't exist.

The encryption key can also be put in `ENV["RAILS_MASTER_KEY"]`, which takes
precedence over the file encryption key.

In addition to that, the default credentials lookup paths can be overridden through
`config.credentials.content_path` and `config.credentials.key_path`.
```

On peut donc faire ce qui est proposé au dessus avec les bonnes clés et versionner le `config/credentials/development.key`, ce qui fait que c'est iso avec la prod.

Faudra donc remanier le fichier de base pour flip les env dev/tests.

**Comment by cyril** [comment]
> Si je comprends bien finalement tu proposes de repasser sur un fichier de config ?

Finalement, suite au retour de @brindu, j'abandonne l'idée des fichiers `.env` au profit de la solution _Rails way_ des credentials, si toi aussi ça te va. Juste y'a quelques détails que j'aimerais clarifier (je les liste un peu plus bas dans ce message).

> On peut donc faire ce qui est proposé au dessus avec les bonnes clés

Oui, depuis Rails 6 on peut avoir un fichier chiffré par environnement ✨

Comme tu le disais et je te suis, pour pouvoir pleinement développer et/ou faire tourner le projet sans avoir à récupérer les infos depuis ansible💩 (aucun contributeur externe ne peut travailler sur ce repo), une solution serait d'utiliser un fichier `config/credentials/development.yml.example` qui aurait le même but que le traditionnel fichier `.env.development.local.example`. Comme ça, on montre un exemple de toute nos clés (avec des valeurs obfusquées), et n'importe qui peut se créer localement son propre fichier avec sa propre clé `config/credentials/development.key` (non versionnée) pour pouvoir faire fonctionner le code. Par exemple dans ma PR en cours j'ai expérimenté et ça donne : https://github.com/etalab/admin_api_entreprise/blob/8449291665c6fa43e64676c960fc11c88160d480/config/credentials/development.yml.example

J'aimerais bien avoir vos avis sur toussa. Ou si ce que je dis n'est pas clair dites le moi aussi 😂

Quelques détails que j'aimerais clarifier, pas bien clair pour moi :

1. A-t-on besoin de versionner le fichier chiffré des clés/valeurs de l'environnement de développement ? Personnellement je pense que non. Nous pourrions préférer pouvoir en avoir chacun un distinct (avec parfois des valeurs identiques, parfois des valeurs différentes). C'est un peu comme le fichier `.env.development.local` (lui ne doit pas être versionné, comme mentionné ici https://github.com/bkeepers/dotenv).
2. Si on versionne le fichier chiffré des clés/valeurs de l'environnement de développement, je propose de le déplacer (actuellement il est ici : `config/credentials.yml.enc`) vers : `config/credentials/development.yml.enc`.
3. Qu'en est-il de l'environnement de test ? A mon avis, on ne devrait pas avoir besoin de nous ajouter un fichier de credentials pour cet environnement.
