### ISSUE TITLE
Ajouter un avertissement au niveau du transfert de compte

### ISSUE THREAD

**Issue by Samuelfaure** [etalab/admin_api_entreprise#1121]
Discussion basecamp https://3.basecamp.com/4318089/buckets/24596643/documents/6212369662

Si un client transfère un compte vers un autre utilisateur, la demande de création de compte MonComptePro de l'autre utilisateur sera refusée s'il utilise une  adresse email non pro (exemple: @gmail)

Ajouter un avertissement pour prévenir ça.

Exemple de wording:
```
Attention: La demande de création MonComptePro risque d'être refusée pour une addresse email générique non professionnelle
Exemple valide:@beta.gouv.fr
Exemple invalide: @gmail
```

**Comment by DorineLam** [comment]
À voir avec @skelz0r si c'est pas du côté de mon compte pro.

Vu avec @Charlottecho l'enjeu ici c'est que un utilisateur qui veut accéder à API Entreprise doit avoir une adresse avec un nom de domaine de l'organisation figurant sur la demande d'habilitation de l'ancien propriétaire du compte.

**Comment by DorineLam** [comment]
De mon côté, je suis vraiment pour ta proposition de "renouvellement de demande". C'est beaucoup plus logique juridiquement. 

J'ai simplement quelques doutes sur la facilité à mettre en place ce système. Si je comprends bien, le scénario serait le suivant : 

1. La personne qui transfère l'habilitation clique sur le bouton "transférer mon habilitation".
2. On lui explique qu'un lien vers une copie de l'habilitation va être envoyé à l'adresse e-mail de son choix du même nom de domaine
- Ici comment fait-on pour permettre à un usager qui a une autre adresse e-mail d'accéder à une copie de la demande ?
- Allons nous accepter d'autres noms de domaine ?
- Comment permettre que ce nouveau user garde l'historique des jetons précédents, les stats et compagnie ?

Je me pose une question aussi, Si les éléments ci-dessus ne sont pas faciles à régler : est-ce qu'on a fréquemment ces demandes de transfert de compte ? Et du coup est-ce que ça vaut le coup de tout changer dans le cas où ça serait compliqué à mettre en place ?

**Comment by skelz0r** [comment]
Une solution simple serait de permettre à n'importe quel utilisateur de dupliquer une demande (je ne sais pas si c'est possible d'un point de vue métier/juridique (ni technique d'ailleurs mais c'est une autre histoire)).

**Comment by skelz0r** [comment]
Au passage, l'email de transfert est assez explicite quand même: https://github.com/etalab/admin_api_entreprise/blob/develop/app/views/user_mailer/transfer_ownership.html.erb#L20

**Comment by Samuelfaure** [comment]
ouais mais c'est trop tard quand tu reçoit l'email et ça ne fais pas mention du fait que tu seras refusé avec gmail

**Comment by skelz0r** [comment]
Oui ofc, c'était une simple remarque (et potentiellement pomper du wording)
