### ISSUE TITLE
Connexion impossible en local avec MonComptePro

### ISSUE THREAD

**Issue by guillett** [etalab/admin_api_entreprise#1128]
J'ai installé en local, avec Docker, cette application.

Après les migrations, je tente de me connecter et je suis redirigé vers cette adresse `https://app-test.moncomptepro.beta.gouv.fr/oauth/authorize?client_id=4442bfd8caac8e19ff202d33060edcd248592662d5a8098e28b706ba906fe9e0db95ad336c38248f42896db272990b8dfc969d8b8857101dabf9b2ffe7ec49b9&redirect_uri=http%3A%2F%2Fentreprise.api.localtest.me%3A5000%2Fauth%2Fapi_gouv_entreprise%2Fcallback&response_type=code&scope=openid+email&state=1aa2f96db0704ed449e42ba1718ecafe44193a3b1b4593c1` et j'obtiens le message suivant :

> Erreur 400
>            invalid_redirect_uri: redirect_uri did not match any of the client's registered redirect_uris

![Screenshot 2023-07-12 at 11-26-28 MonComptePro](https://github.com/etalab/admin_api_entreprise/assets/1410356/d71e3fff-5af2-41e9-8734-141504d7caef)

J'ai tenté depuis http://entreprise.api.localtest.me:5000/compte/se-connecter et http://particulier.api.localtest.me:5000/compte/se-connecter

Est ce possible de reconfigurer l'app MCP en dev pour permettre ces tests là ?

Merci.

**Comment by skelz0r** [comment]
Cela m'étonne car cela fonctionne pour moi.

Je vais creuser voir.

**Comment by skelz0r** [comment]
Ok, en fait aujourd'hui ça ne marche plus même sur le 3000 (la semaine dernière ce n'était pas le cas).

Je vais creuser ça.

**Comment by guillett** [comment]
Merci beaucoup !

**Comment by skelz0r** [comment]
C'est réglé. Désolé pour le dérangement c'était en effet une mauvaise config pour le local.

Je close ici.
