### ISSUE TITLE
Better User destroy

### ISSUE THREAD

**Issue by hugolepetit** [etalab/admin_api_entreprise#14]
Today user destroy will wipe : 
- contact details
- reference of foreign_key in jwt_api_entreprise

Feelsbad to orphan jwt_api_entreprise. Either we wipe them, or we keep a trace of the original user to be able to sort them and have a boolean "orphaned" set to true. We can keep it anonymous by having a  user email like "m*****@g****.com" for maxime@gmail.com user destroyed

**Comment by skelz0r** [comment]
No longer relevant -> user destroy nullify authorization request
