### ISSUE TITLE
Refactoriser dans une vue partagé la modal

### ISSUE THREAD

**Issue by skelz0r** [etalab/admin_api_entreprise#234]
Vu qu'il y a déjà une modal ça pourrait être pas mal de potentiellement refactor la vue. 

Ça peut se faire dans une issue à part.

_Originally posted by @skelz0r in https://github.com/etalab/admin_api_entreprise/pull/233#discussion_r752201396_

**Comment by Samuelfaure** [comment]
C'est fait depuis qu'on a implémenté turbo non? Enfin c'est ce que je comprend de doc/modal.md

**Comment by skelz0r** [comment]
Oui
