### ISSUE TITLE
Ne pas envoyer de mail de renouvellement de jeton blacklisté

### ISSUE THREAD

**Issue by skelz0r** [etalab/admin_api_entreprise#274]
Les clients ayant des jetons blacklistés peuvent recevoir des mails avertissant de l'expiration des-dits jetons.

Cela est source de confusion et il faudrait donc ne pas envoyer ces mails le cas échéant.

Reporté initialement [ici](https://github.com/etalab/dashboard_api_entreprise/issues/145)

**Comment by skelz0r** [comment]
@Samuelfaure peux-tu affiner / pointer pourquoi tu as ouvert ce ticket ? Dans le code clairement on exclut les jetons blacklistés Cf https://github.com/etalab/admin_api_entreprise/blob/develop/spec/organizers/token/send_expiration_notices_spec.rb#L41 et https://github.com/etalab/admin_api_entreprise/blob/develop/app/interactors/token/retrieve_expiring.rb#L6

**Comment by Samuelfaure** [comment]
Reçu un message sur le support d'un client se plaignant de recevoir des mails de renouvellement (expiration dans 3 mois) alors que son token ne va pas expirer.

Il a un jeton blacklisté qui "va expirer" dans 3 mois, d'où ma conclusion que le mail concernait ce jeton blacklisté.

Je vais creuser du coup.

**Comment by skelz0r** [comment]
@Samuelfaure as-tu l'id du jeton surtout, c'est ça qui est intéressant.

**Comment by skelz0r** [comment]
Ou tout du moins l'id du user

**Comment by skelz0r** [comment]
Je close au profit de #296
