### ISSUE TITLE
Changement du menu de gauche

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#278]
En tant qu'admin quand on va voir les statistiques d'un jeton on se retrouve dans la vue utilisateur et on ne voit plus les menus administrateurs.

Un simple précédent dans le navigateur permet d'y revenir bien sûr, mais est-ce intentionnel ?

**Comment by skelz0r** [comment]
> Un simple précédent dans le navigateur permet d'y revenir bien sûr, mais est-ce intentionnel ?

Pour le moment on oriente l'ensemble des devs sur les users, en attente du sort de la partie admin.

**Comment by brindu** [comment]
> En tant qu'admin quand on va voir les statistiques d'un jeton on se retrouve dans la vue utilisateur et on ne voit plus les menus administrateurs.

Yes atm le menu (simple user ou admin) dépends de l'action derrière la requête et non du type de user.

**Comment by Haelle** [comment]
on clos au profit de Metabase
