### ISSUE TITLE
Impossible de se déconnecter en tant qu'admin

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#279]
Il n'y a pas de bouton pour se déconnecter en tant qu'administrateur, ça m'arrive de temps en temps d'avoir à le faire (pour prendre une capture d'écran de login pour l'envoyer au support).

Et donc je vais sur la page de détail d'un jeton pour cliquer sur le bouton qui lui est accessible en tant qu'utilisateur cf #278 

P.S: je pourrait nettoyer les cookies et les données du sites via le navigateur, mais c'est pas pareil ! 😁

**Comment by skelz0r** [comment]
Ce bouton va partir en header bientôt.

Je closerai ce ticket dans la foulée.
