### ISSUE TITLE
Envoi de relance sur jetons blacklistés/archivés

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#296]
J'ai l'impression au vu de [ce ticket](https://support.etalab.gouv.fr/#ticket/zoom/36568) de support que nous envoyons des relances de renouvellement de jetons mêmes s'ils sont archivés ou blacklistés.

Si c'est bien cela il faudrait couper cette fonctionnalité ; si c'est autre chose investiguer.
Les relances [sont visibles dans Mailjet](https://app.mailjet.com/contacts/overview/21MMha) avec les dates mais ne permettent pas de savoir de quel jeton il s'agit. Cependant le dernier jeton actifs (non blacklistés ou non archivés) n'expire pas de suite !

**Comment by skelz0r** [comment]
Duplicate https://github.com/etalab/admin_api_entreprise/issues/274

**Comment by skelz0r** [comment]
Le code qui retrieve les jetons exclut les jetons blacklistés et archivés https://github.com/etalab/admin_api_entreprise/blob/develop/app/interactors/token/retrieve_expiring.rb

Le mail est parti le 10/12/2021, pour une expiration dans 3 mois, il s'agit bien du jeton blacklisté ET archivé.

Faut creuser voir pour harden potentiellement ce comportement.

**Comment by Haelle** [comment]
ok donc ça ne fonctionne pas, le dernier mail est parti en janvier.

ça devrait être blacklisté **et/ou** archivé je pense

**Comment by brindu** [comment]
Je vais regarder ça.

**Comment by skelz0r** [comment]
J'ai creusé un peu aussi, j'ai fait un test spec/interactors/token/retrieve_expiring_spec.rb et tout est green, dunno understand.

**Comment by skelz0r** [comment]
> Je suis quasi certain que le mail vient de la seconde machine watchdoge qui n'est pas en frontale...

AH, et du coup c'est pas blacklisté/archivé sur cette machine ?

**Comment by brindu** [comment]
Il y a pas de duplication des bases entre les deux machines quand tu archives/blacklistes c'est uniquement sur la machine frontale. L'envoie des mails est coupé depuis la machine non frontale pour éviter les doublons (c'est géré avec un booléen dans le Ansible). La base est censée être mise à jour via import du dernier dump de prod (lors d'un switch par exemple). 

Le process est détaillé [ici](https://3.basecamp.com/4318089/buckets/14299506/documents/3227384071). Je vérifie, si changement de serveur il y a eu une étape est peut être passée à la trappe... Notamment ce booléen pour couper les mails sur la seconde machine.

**Comment by skelz0r** [comment]
Faut vraiment scripter en 1 ligne le switch parce que c'est error prone over 9000 🙄

**Comment by brindu** [comment]
Alors les deux bases (sur les deux machines) sont à jour et identiques pour ce user et ses jetons (ie il est blacklisté partout et aucune notif ne partira à présent). Ma théorie c'est que les machines ont été swap récemment (après la dernière notif envoyée le 10 janvier) et à présent les bases sont alignés et plus de mails ne partiront pour ce jeton. 

Je pense que c'est confirmé par l'état du Ansible... La tout de suite c'est _wd2_ en frontale et _watchdoge_ en arrière plan. Sauf que c'est l'inverse dans le Ansible : 

<img width="256" alt="Capture d’écran 2022-01-25 à 11 41 24" src="https://user-images.githubusercontent.com/4283958/150962458-a8c0cc65-e77e-4349-9736-4777313ca3d6.png">

On peut savoir ce qu'il se passe côté OPS genre qui swap quelles machines et quand ?! Entre ça et les logs Elasticsearch manquant c'est vraiment relou de pas savoir ce qu'il se passe.

**Comment by skelz0r** [comment]
En ce moment en plus on switch souvent pour les mises à jour système. Vois avec Aurélien du coup.

**Comment by brindu** [comment]
Bon je ne sais pas d'où ça peut venir : 
* les serveurs ont été swap correctement (il y a eu un soucis avec logstash mais sans rapport avec ce ticket)
* les bases sont identiques sur les deux machines 
* les mails ne partent pas en doublons (uniquement de la machine frontale) 
* je n'ai aucune trace en base de l'envoie de la notification (qui est normalement save) 
* vu le ticket pas de doutes l'email a bien été envoyé (idem on a la trace dans mailjet) 
* puisqu'il a reçu la notif pour les 90 jours le 10 décembre il aurait dû recevoir la suivante pour les 60 jours aux alentours du 10 janvier 

Du coup je me suis dit que c'était potentiellement l'usager qui aurait reçu le mail le 10 décembre, on blacklist le jeton entre temps, il traite cet email quelques semaines plus tard mais là même pas : dernière update du jeton le 7 octobre l'année dernière avant le mail du 10 décembre. Et de toute façon toujours aucune trace en base de cette notif à 90 jours envoyée. 

On leur demande de surveiller s'ils reçoivent ce genre d'email par la suite ? J'ai plus trop d'idées là. Si besoin il y a des backups quotidiens donc aussi la possibilité d'importer un dump à date pour investiguer.

@am-beta PI

**Comment by Haelle** [comment]
je clos ; si ça revient on rouvrira
