### ISSUE TITLE
Datapass non notifié des transferts de compte

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#297]
J'ai l'impression que Datapass n'est plus notifié des transferts de comptes... cf [ce ticket](https://support.etalab.gouv.fr/#ticket/zoom/36942) 

Et en effet j'ai l'impression que le mailer `UserMailer.notify_datapass_for_data_reconciliation` n'est plus utilisé que c'est du code mort !

https://github.com/etalab/admin_api_entreprise/blob/6e931bbd0249619de32ef5196a879cd2a0e44c8b/app/mailers/user_mailer.rb#L12

**Comment by skelz0r** [comment]
En effet, ce n'est plus utilisé dans le code.

Par contre, je ne vois pas à quoi ça sert vu que c'était dans une tâche `OAuthAPIGouv::Tasks::RetrieveUserInfo`, elle-même dans un Login 🤷

C'est quoi l'objectif ici ?

PS: Je n'ai pas accès au ticket.

**Comment by Haelle** [comment]
Si je comprends bien le code, on : 
1. transférait le jeton sur un nouvel email quand l'utilisateur cliquait sur "Transférer le compte"
2. ce nouvel email se connecte (et ainsi on est sûr qu'il a un compte auth API gouv
3. on notifie Datapass que cette personne est la nouvelle titulaire de la demande

Je pensais que c'était fait lors du click mais c'était fait à la première connexion de l'usager pour être sûr qu'il existe côté auth. @brindu tu confirmes ?

P.S: j'ai rapatrié le ticket sur API Entreprise

**Comment by skelz0r** [comment]
Oui je comprends la même chose.

En lisant le ticket, je comprends mieux à quoi ça sert. 

Pourquoi on n'envoi pas la commande exacte à effectuer pour ce transfert btw ? C'est très brainfuck d'avoir un mail aussi formel pour ce qui semble être une flemme d'exposer une API 😅

**Comment by brindu** [comment]
> Je pensais que c'était fait lors du click mais c'était fait à la première connexion de l'usager pour être sûr qu'il existe côté auth. @brindu tu confirmes ? 

Je confirme que c'est bien au premier login du nouveau propriétaire qu'on fait la notif à DataPass. L'objectif étant que le nouvel utilisateur puisse aussi accepter à la demande DataPass associée. 

> Pourquoi on n'envoi pas la commande exacte à effectuer pour ce transfert btw ? C'est très brainfuck d'avoir un mail aussi formel pour ce qui semble être une flemme d'exposer une API 😅 

OUI. 
C'était à la demande de Raphaël. C'était censé être temporaire, ils devaient faire en sorte que les formulaires de demandes d'accès soient accessibles par tous les utilisateurs d'une même organisation pour ne pas faire avoir à faire ce swap de propriétaire.

**Comment by skelz0r** [comment]
> C'était censé être temporaire, ils devaient faire en sorte que les formulaires de demandes d'accès soient accessibles par tous les utilisateurs d'une même organisation pour ne pas faire avoir à faire ce swap de propriétaire.

@rdubigny quid ici ?

Si ce n'est pas le cas je vais rebrancher ce mailer.

**Comment by skelz0r** [comment]
Je pose rapidement un breakdown:

* [ ] Introduire un organizer `User::Login` qui retrieve et notifie Datapass si on update le oauth_id
* [ ] Refactor `SessionsController#create` pour utiliser l'organizer ci-dessus

C'est un peu brainfuck comme bricolage tout de même, le mieux serait d'introduire une API publique sur DataPass pour qu'on fasse nos calls.

**Comment by Haelle** [comment]
vu IRL ; on reste sur une solution où on notifie Datapass des changements à faire. S'ils veulent qu'on passe par une API, faut qu'ils en fassent une. Vu à quel point on le fait peu souvent pas sûr que ça soit tout de suite.

**Comment by brindu** [comment]
Du coup je clos.

**Comment by skelz0r** [comment]
@brindu je ré-ouvre parce qu'on doit quand même envoyer un email.

Pour simplifier imo on shoot directement un email lors du transfert au lieu d'attendre que le user se connecte vraiment un jour.

**Comment by brindu** [comment]
> @brindu je ré-ouvre parce qu'on doit quand même envoyer un email. 

OUPS 🙊

**Comment by Haelle** [comment]
un petit up car on a un nouveau cas de support là dessus et l'email n'a pas été envoyé

**Comment by skelz0r** [comment]
@brindu tu prends ?

**Comment by brindu** [comment]
Je m'en occupe dès demain !

**Comment by brindu** [comment]
Bon en fait on ne réconcilie même plus l'ID OAuth API Gouv pour les nouveaux utilisateurs créés par un transfer de compte. On a 72 users en base sans ID technique API Gouv, je vais corriger tout ça.
