### ISSUE TITLE
Update des users lors des connexions (beaucoup de users valides n'ont pas de prénom/nom)

### ISSUE THREAD

**Issue by skelz0r** [etalab/admin_api_entreprise#301]
Je suis entrain de travailler sur le header global où l'on fait apparaître les infos de l'utilisateur (prénom/nom) et je me rends compte qu'on a plein de users dont la demande a été validé sans prénom/nom

```
irb(main):023:0> AuthorizationRequest.joins(:user).where(authorization_requests: { status: 'validated' }, users: { first_name: nil, last_name: nil }).count
=> 303

irb(main):026:0> AuthorizationRequest.joins(:user).where(authorization_requests: { status: 'validated' }).count
=> 434
```

Je pense que ce sont des relicats de vieux users, sur les 2 derniers mois tout est OK:

```
irb(main):031:0> AuthorizationRequest.joins(:user).where(authorization_requests: { status: 'validated', created_at: (2.month.ago..Time.now) }, users: { first_name: nil, last_name: nil }).count
=> 0
```

C'est un peu facheux tout de même ...

Je propose donc, lors d'une connexion sur api-auth, de refetch les infos de api-auth à chaque fois, histoire d'avoir une autorité qui fait foi ET aussi combler petit à petit les problèmes.

**Comment by Samuelfaure** [comment]
@Haelle On peut close si Wontfix?

**Comment by Haelle** [comment]
Si tu penses qu'il n'y a pas de Quick win close it ! 🚪

**Comment by Samuelfaure** [comment]
je ferme parce que trop d'issues toute façon, les backlogs c'est le mal
