### ISSUE TITLE
🔥 Bouton renouveler ou étendre mes droits ne fonctionne plus

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#316]
Ce bouton ne fonctionne plus car il envoie un POST mais ça devrait envoyer un GET. Ça envoie un POST car c'est un bouton de type `submit`... J'imagine que ça va de paire avec le design...

https://github.com/etalab/admin_api_entreprise/blob/3e156d15f6803e6700701511187ceddf72925b79/app/views/jwt_api_entreprise/_jwt_api_entreprise.html.erb#L68

**Comment by skelz0r** [comment]
closed by https://github.com/etalab/admin_api_entreprise/commit/e486b69b14bf8f4a0d01963d7e2f02503db835e6
