### ISSUE TITLE
Environnement de développement rejetté par api.gouv.fr

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#320]
En lançant le serveur en local (avec l'auth distante) ; 
j'ai l'impression que nous ne pouvons plus faire de tests en local : 
![image](https://user-images.githubusercontent.com/5159985/153833550-b6491ce5-382a-4517-adaa-3f10b602500f.png)

**Comment by Samuelfaure** [comment]
Cette URL fonctionne: `http://localhost:3000/`

Ces URLS ne fonctionnent pas:
`http://v3-beta.entreprise.api.gouv.local:3000/`
`http://dashboard.entreprise.api.gouv.local:3000/`

A noter que se log sur la première ne répercute pas les autres

Bug peu important pour le moment, on a pas particulièrement besoin de se logguer en V3

**Comment by Haelle** [comment]
bon ok le problème est chez moi, en navigation privée ça fonctionne.

J'ai l'impression qu'il y a un cookie que je n'arrive pas à supprimer...

**Comment by Samuelfaure** [comment]
Chez moi avec les URL 2 et 3 en privé ne fonctionne pas.

**Comment by skelz0r** [comment]
Y'a que localhost qui fonctionne.

Après on peut demander à Raph de les rajouter.
