### ISSUE TITLE
Mettre des ancres dans la doc métier

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#329]
Mettre des ancres dans la doc métier des champs

![image](https://user-images.githubusercontent.com/5159985/154041554-d89bebbf-ed4b-4208-8794-bd4ca86e7d46.png)

**Comment by skelz0r** [comment]
Already done https://v3-beta.entreprise.api.gouv.fr/endpoints/insee/unites_legales_diffusibles#property_attribute_numero_tva_intracommunautaire

**Comment by Haelle** [comment]
En effet, ça suffit pour le moment, à terme faudrait pouvoir les copier rapidement
