### ISSUE TITLE
Jeter l'espace admin

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#380]
Aujourd'hui ça n'apporte que des bugs ; on a Metabase pour consulter la donnée

**Comment by skelz0r** [comment]
Y'a une action qui peut potentiellement servir -> transférer des comptes.

Est-ce que c'est actuellement utilisé ?

**Comment by skelz0r** [comment]
Nan mais en fait https://github.com/etalab/admin_api_entreprise/issues/377 solve le problème.
