### ISSUE TITLE
Qualification des utilisateurs

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#391]
Qualifier la base de données pour savoir : 
- qui est un éditeur
- par quel éditeur ce client passe-t-il

Attention ; il s'agit d'améliorer la qualification du stock existant dans une premier temps puis la récupération via Datapass et enfin de penser à l'envoie d'informations au CRM dans un second temps.

**Comment by skelz0r** [comment]
is it still relevant ?

**Comment by Samuelfaure** [comment]
is it still relevant ?

**Comment by Haelle** [comment]
on peut en effet clore pour le moment mais oui c'est toujours d'actualité.

Dans notre back-office faut qu'on puisse sortir la liste des éditeurs facilement avec un booléen ou autre ; et donc modifier le Datapass en conséquence voir faire un Datapass dédié pour les éditeurs en fait...

!later
