### ISSUE TITLE
Supprimer l'env de staging

### ISSUE THREAD

**Issue by skelz0r** [etalab/admin_api_entreprise#399]
Elle existe bien, mais alors .. quel est l'intérêt ?

**Comment by brindu** [comment]
C'était pour proposer un dashboard à la DGFIP. Ils n'ont rien pour monitorer leurs services (derniers calls, nombre d'erreurs, etc) donc on avait setup cet environnement pour eux.

Pas certain qu'ils l'aient vraiment utilisé.

**Comment by skelz0r** [comment]
Ok, donc Metabase fait/fera clairement le taff vu que dtf y'a plus de monitoring sur le dashboard.

Let's flip it
