### ISSUE TITLE
Upgrade to dry-validation v1

### ISSUE THREAD

**Issue by brindu** [etalab/admin_api_entreprise#4]
https://dry-rb.org/news/2019/06/10/dry-validation-1-0-0-released/

The gem reform must be compatible with the first release of dry-validation

**Comment by cyril** [comment]
Pour info, les nouvelles versions ne proposent plus la [méthode `confirmation`](https://dry-rb.org/gems/dry-validation/0.13/basics/macros/#confirmation) 👀
