### ISSUE TITLE
Jeton non affiché dans l'espace personnel

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#412]
Une utilisatrice ne voit qu'un seul de ses deux jetons, on sait d'où ça vient ?

![image](https://user-images.githubusercontent.com/5159985/165463301-bd5e2c59-8497-43ab-b6f2-ae58eff7f33a.png)

Cf côté Datapass : 

![image](https://user-images.githubusercontent.com/5159985/165462785-77276a0b-914e-49b3-a8b7-28cfaace3775.png)

Il est prévu d'harmoniser la vue côté admin et utilisateur ?

**Comment by skelz0r** [comment]
Je check.

> Il est prévu d'harmoniser la vue côté admin et utilisateur ?

Je ne comprends pas cette phrase.

**Comment by skelz0r** [comment]
Je viens de checker, à la lumière de https://github.com/etalab/admin_api_entreprise/blob/develop/app/controllers/authorization_requests_controller.rb#L5 il s'avère que le coupable est le scope `submitted_at_least_once`, il y a (encore...) un problème d'intégrité de données...

**Comment by skelz0r** [comment]
Ce sont des "vieilles" demandes, datant du moment où les demandes ont été introduites en db.

La seule date valide sur ces vieilles demandes sont les `validated_at`, récupérées depuis les jetons (on faisait la création du jeton au moment de la validation). 

Vu que cette donnée (`first_submitted_at`) n'est pas réellement relevant pour le moment, je vais prendre cette valeur là (`validated_at`) et la coller dans le `first_submitted_at`)

Je vais executer la commande suivante pour fixer le problème:

```ruby
AuthorizationRequest.where.not(validated_at: nil).where(first_submitted_at: nil).find_each { |ar| ar.update(first_submitted_at: ar.validated_at) }
```

Ok pour toi @Haelle ?

**Comment by Haelle** [comment]
Ok pour moi

> Je check.
> 
> > Il est prévu d'harmoniser la vue côté admin et utilisateur ?
> 
> Je ne comprends pas cette phrase.

Voilà ce que JE vois : 
![image](https://user-images.githubusercontent.com/5159985/165479018-e1d76b7e-28f1-436d-a365-c100a2910b52.png)

Et ce qu'ELLE voit : 
![image](https://user-images.githubusercontent.com/5159985/165479066-fc3b2106-f3e6-4084-9d49-5f6cb0608c37.png)
