### ISSUE TITLE
Nettoyer les tests sur la db dans les modèles

### ISSUE THREAD

**Issue by skelz0r** [etalab/admin_api_entreprise#425]
Tous les `have_db_column` and stuff, aucun intérêt modulo casser les tests quand on fait des migrations/ignore columns 🤷

**Comment by brindu** [comment]
Ça me choque pas trop d'avoir à update les tests à l'ajout de migration, mais fondamentalement pas trop d'avis si on décide de supprime cette couche de tests.

**Comment by skelz0r** [comment]
> Ça me choque pas trop d'avoir à update les tests à l'ajout de migration

fonctionnellement ça n'apporte rien de tester ça (ça fait même pas office de unit test)

Comme tu t'en fiches, je vais juste clean.
