### ISSUE TITLE
Permettre la class {:.fr-highlight} dans les fiches métiers

### ISSUE THREAD

**Issue by DorineLam** [etalab/admin_api_entreprise#461]
Actuellement, la class {:.fr-highlight} n'est pas correctement rendue graphiquement.

Exemple visible avec l'attestation de vigilance : 
<img width="562" alt="Capture d’écran 2022-05-07 à 15 23 38" src="https://user-images.githubusercontent.com/46896006/167256315-25e0fe37-4c4d-4f03-8ea5-2e3e7c4099a2.png">

**Comment by skelz0r** [comment]
C'est déjà le cas. Juste dans ce cas précis il manque un saut de ligne.
