### ISSUE TITLE
Test search algolia FAQ qui explose les 10k search / mois

### ISSUE THREAD

**Issue by skelz0r** [etalab/admin_api_entreprise#467]
Aucune idée de comment ça a pu arriver 🤷

<img width="983" alt="Screen Shot 2022-05-12 at 10 38 20" src="https://user-images.githubusercontent.com/1279968/168029185-42f7ca8b-b7c7-483d-9e9c-652283e5e5fe.png">

Je peux pas avoir accès au détail sans upgrade (c'est mort), du coup dunno 🤷

Des pistes: 

* les N retry des tests qui failent => 3 calls / CI.

**Comment by Samuelfaure** [comment]
![image](https://user-images.githubusercontent.com/14159757/189332659-2dbe874a-069d-4893-8df9-5d73fa8f44cf.png)

Je pense qu'on peut fermer ici :relaxed:
