### ISSUE TITLE
Mock les données d'appel SIADE depuis sandbox

### ISSUE THREAD

**Issue by Samuelfaure** [etalab/admin_api_entreprise#487]
Comme pour le dev actuellement

À discuter

**Comment by skelz0r** [comment]
sandbox tu veux dire ? staging on va le drop imo

**Comment by skelz0r** [comment]
<img width="1302" alt="Screen Shot 2022-08-25 at 09 38 16" src="https://user-images.githubusercontent.com/1279968/186605167-766f7d71-1bf2-4538-a3b6-6255a0d02dae.png">

ça marche plus !

Si c'est pas la prod, c'est forcément development et sandbox, je propose de faire des seeds avec des jetons de staging (qu'on génère à la volée) avec différents droits.

**Comment by Samuelfaure** [comment]
franchement la flemme ici? je vote pour se débarrasser de ce backlog, je trouve la valeur ajoutée pas forcément worth it point de vue ROI
