### ISSUE TITLE
Migrer le monitoring api watchdoge

### ISSUE THREAD

**Issue by skelz0r** [etalab/admin_api_entreprise#507]
Y'a 2 endpoints: 

* https://entreprise.api.gouv.fr/watchdoge/dashboard/current_status
* https://entreprise.api.gouv.fr/watchdoge/stats/provider_availabilities?period=ParamètreDeLaPeriode&endpoint=ParamètreDuEndpoint

Après ça, on pourra flip watchdoge

**Comment by Haelle** [comment]
Faut voir si on veut vraiment garder ces API... si on a que 1/2 usager on va négocier avec eux de s'inscrire à InStatus

**Comment by skelz0r** [comment]
L'introduction de vrai routes de ping va solve ça.

Instatus ça a 0 intérêt programmatiquement.

**Comment by skelz0r** [comment]
Autre solution temporaire: on backport juste ce qu'il faut ici, vu que dtf le driver ELK a été migré.

**Comment by Haelle** [comment]
il n'y a plus de données dans ELK, ça ne sert à rien, d'ailleurs faudrait aussi purger cette dette

**Comment by Haelle** [comment]
Ok ça a dû être réparé car je suis allé plusieurs fois sur Kibana et il n'y avait aucune données et là en effet c'est de nouveau fonctionnel

**Comment by skelz0r** [comment]
🤷

**Comment by skelz0r** [comment]
Bon par contre là ça ne marche plus depuis un moment, du coup on n'a plus de stats d'usage de jetons

**Comment by skelz0r** [comment]
Je close au profit de https://github.com/etalab/admin_api_entreprise/issues/893
