### ISSUE TITLE
Revert le revert de Matomo + fix le problème

### ISSUE THREAD

**Issue by Samuelfaure** [etalab/admin_api_entreprise#559]
La PR matomo (features/matomo) nous a fait péter la prod :sweat_smile: 

Faut la réparer et la remerger

**Comment by skelz0r** [comment]
On a un petit souci cf 8d9f6ad9

Je me (re(re))penche dessus.

**Comment by skelz0r** [comment]
Closed by 67836940bbf0154aa3749cc05a6876d12b986deb
