### ISSUE TITLE
Réparer lien modal turbo qui fonctionne mal

### ISSUE THREAD

**Issue by Samuelfaure** [etalab/admin_api_entreprise#566]
![image](https://user-images.githubusercontent.com/14159757/175546780-f69cb037-4b2f-444b-9bd9-8a20d9cd1550.png)

Quand on clique sur ce bouton, après avoir ouvert le site sur une nouvelle page, souvent ça ne marche pas... Pourquoi??

J'ai cherché un moment mais pas trouvé

**Comment by skelz0r** [comment]
imo faut aussi watch `turbo:render`

**Comment by Samuelfaure** [comment]
J'avais bien regardé la page de doc mais pas trouvé d'event qui serait + approprié que `turbo:load`

Je vais faire une tentative avec `turbo:render`
