### ISSUE TITLE
L'email de renouvellement se trompe de N° Datapass ?

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#568]
Cette personne a déjà renouvelé son jeton une fois N°2970 -> 11244 et là la seconde demande expire et le lien qui est envoyé dans l'email essaie de faire une copie de la première demande : https://datapass.api.gouv.fr/copy-authorization-request/2970

Ce qui échoue côté Datapass, il faudrait que ça génère un lien du type : https://datapass.api.gouv.fr/copy-authorization-request/11244

CF : https://support.etalab.gouv.fr/#ticket/zoom/44228

**Comment by skelz0r** [comment]
Titre du mail: "%{user_full_name} 🔑 Renouvelez dès maintenant votre accès à l'API Entreprise", à 30 jours

**Comment by skelz0r** [comment]
J'ai trouvé: l'ancienne demande d'autorisation n'a pas d'inscrit que des emails de relances aient été lancés, ce qui fait que je ne sais pour quelle raison ceux-ci sont maintenant envoyés.

J'ai mis à jour la demande pour que ça ne se reproduise pas.

Je vais voir comment harden ça (imo c'est ENCORE un effet de bord de l'absence de contraintes d'intégrités de nos données...)

**Comment by skelz0r** [comment]
Je n'ai pas de `previous_external_id` sur l'ancienne demande, je me suis baladé sur DataPass voir le pourquoi du comment, il s'avère que la copie a été refusée ( https://datapass.api.gouv.fr/authorization-request/3406 ).

L'assertion suivante:

> Cette personne a déjà renouvelé son jeton une fois N°2970 -> 11244

est fausse, la copie de 2970 est 3407

Ici on a donc un cas "au limite" où la copie de la demande a été refusé, on a donc aucun moyen techniquement avec le contexte existant de ne plus envoyer d'email.

Une potentiellement solution serait de permettre de ne plus recevoir d'email de relance du jeton (via un lien d'unsubscribe). wdyt @DorineLam @Haelle ?

**Comment by Haelle** [comment]
Je ne pense pas que les gens vont se désinscrire tout seul, par peur de ne pas recevoir les futurs alertes. On garde l'idée pour le moment.

Merci beaucoup pour cette analyse car le sujet est récurrent 🙏
Mais au final c'est un cas particulier auquel j'aurai pu trouver l'explication seul 😔... Je propose de refaire l'exercice (moi même et avec @skelz0r au besoin) lorsque le prochain cas se présente voir si c'est la même situation.

**Comment by skelz0r** [comment]
Je pense en effet que ton wording est plus adapté. Par contre, peux-tu donner le lien de ce bouton ? Je ne crois pas que l'on gère ça sur la stack, et si ce n'est pas le cas il faudrait fixer (car cela donnerait une 404).

**Comment by DorineLam** [comment]
Ok je viens de remplacer le wording.
Voici ce qu'il y a dans le lien : [[WORKFLOW_EXIT_LINK_FR]]

**Comment by skelz0r** [comment]
lolwat, cette variable ne correspond absolument à rien dans notre code (et clairement vu le nom ça a 0 chance) + si on google cette variable ça ne donne rien.

Je pense donc que ce lien ne marche pas (et d'ailleurs.. est-ce que ça produit un lien ???) ou alors j'ai loupé un truc et ça doit être défini quelque part dans le template (?)

**Comment by DorineLam** [comment]
Je ne sais pas 😅 du tout

**Comment by skelz0r** [comment]
Possible d'envoyer un exemple pour voir ?

**Comment by DorineLam** [comment]
Oui je peux, je t'envoie ça
