### ISSUE TITLE
[Fiche métier] Rendre le nom du fournisseur cliquable vers le site du FD

### ISSUE THREAD

**Issue by DorineLam** [etalab/admin_api_entreprise#575]

**Comment by DorineLam** [comment]
Maquette  : mettre le picto "target_blank" après le FD, qui devient cliquable : 
![Image](https://user-images.githubusercontent.com/46896006/176178454-c46b6d69-e341-4731-a6d8-90642e89e115.png)

**Comment by Samuelfaure** [comment]
Fixed par #564
