### ISSUE TITLE
Écarter les boutons pour télécharger les attestations

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#584]
L'utilisateur croit qu'il n'y a qu'un seul bouton : 

![image](https://user-images.githubusercontent.com/5159985/176644057-99890443-b77e-4bc9-a1ee-e52c3e4ebd4a.png)

Faudrait les écarter

**Comment by Samuelfaure** [comment]
Fixed with https://github.com/etalab/admin_api_entreprise/pull/619
