### ISSUE TITLE
Bug d'affichage des icones dans le compte utilisateur

### ISSUE THREAD

**Issue by DorineLam** [etalab/admin_api_entreprise#592]
Les icônes ne s'affichent plus correctement dans le compte utilisateur : 

<img width="763" alt="Capture d’écran 2022-07-01 à 16 29 06" src="https://user-images.githubusercontent.com/46896006/176914250-480e0b18-9300-444d-8689-fe76a7aeac24.png">
<img width="224" alt="Capture d’écran 2022-07-01 à 16 29 15" src="https://user-images.githubusercontent.com/46896006/176914255-6ed3115f-cb57-4b41-9565-1cf82c6de2bd.png">

**Comment by skelz0r** [comment]
Possible d'avoir les liens ?
Est-ce que ce sont toutes les icones ?

**Comment by DorineLam** [comment]
Oui : 
Sur https://sandbox.dashboard.entreprise.api.gouv.fr/compte/jetons
Bouton transférer un jeton : 
<img width="939" alt="Capture d’écran 2022-07-01 à 17 02 47" src="https://user-images.githubusercontent.com/46896006/176920230-04972c56-fafa-4cf0-a930-deb14d92c3db.png">

Sur les statistiques ausssi : 
https://sandbox.dashboard.entreprise.api.gouv.fr/compte/jetons/05fca903-f359-4238-bc9f-ee85f56bac7a/stats
<img width="1338" alt="Capture d’écran 2022-07-01 à 17 03 04" src="https://user-images.githubusercontent.com/46896006/176920354-2a87702e-16ea-4d62-9287-aadc1155a180.png">

**Comment by skelz0r** [comment]
Très étrange d'avoir des bugs d'affichage que sur certaines icons, je pense que c'est parce que ces icones étaient valables dans une ancienne version du dsfr, et qu'on avait avant un problème de cache.

**Comment by skelz0r** [comment]
Je me penche dessus voir.
