### ISSUE TITLE
Les ancres du guide de migration apparaissent dans les titres

### ISSUE THREAD

**Issue by DorineLam** [etalab/admin_api_entreprise#599]
Ici :  https://entreprise.api.gouv.fr/developpeurs/guide-migration
<img width="977" alt="Capture d’écran 2022-07-05 à 08 07 08" src="https://user-images.githubusercontent.com/46896006/177260917-7779a8c5-0259-4e49-8f54-cf5e5e0ac660.png">

**Comment by skelz0r** [comment]
Après un peu de recherche je ne suis pas sûr que cela soit faisable avec le système actuel. Les ancres sont automatiquement générés en fonction du texte du heading.

Je vais retirer déjà pour que ça soit lisible, et en fonction du besoin on itère (à noter que si on change le texte ça change l'ancre, ce qui peut être problématique, peut-être pas pour le guide cependant où les titres ne devraient pas changer à l'avenir).

**Comment by skelz0r** [comment]
Je retire ce que j'ai dit, y'en a un qui marche, je tente voir des trucs 🤷

**Comment by skelz0r** [comment]
Et en effet j'ai de la doc ici: https://www.markdownguide.org/extended-syntax/#heading-ids

**Comment by DorineLam** [comment]
@skelz0r tu arrives à faire quelque chose pour rendre lisible d'ici 10h ? et pousser en prod ?

**Comment by skelz0r** [comment]
J'ai trouvé: les ancres qui commencent par des numéros ne fonctionnent pas, je m'en occupe et pousse ça en prod

**Comment by DorineLam** [comment]
Merci ! 🙏

**Comment by skelz0r** [comment]
"Fixed" here 439efc8c

Y'en a un que j'ai pas réussi à fixer, dunno why je l'ai du coup retirer (parce que dtf ça génère la même ancre en l'état)

**Comment by skelz0r** [comment]
Je close
