### ISSUE TITLE
[Tableau de bord] Mettre une pop up d'explication quand on clique sur "Renouveler ou étendre mes droits"

### ISSUE THREAD

**Issue by DorineLam** [etalab/admin_api_entreprise#633]
Dans le tableau de bord : 
Actuellement quand on clique sur "Renouveler ou étendre mes droits", on arrive directement sur la page Datapass. L'utilisateur n'est pas accompagné, aucun texte ne lui précise que la demande va être dupliquée ... Que la durée de vue de l'ancien jeton reste identique ...

![Image](https://user-images.githubusercontent.com/46896006/182397866-600b327e-ee6e-4e9f-aa9a-893fe25a1ed9.png)

J'aimerais mettre le système de pop up comme fait acutelllement pour les fonctionnalités de transferts du jeton ou du compte : 

![Image](https://user-images.githubusercontent.com/46896006/182398556-db462700-03d2-4e9f-be30-624f5fccb8ab.png)

Il me faudrait le squelette ci-dessus, le bouton bleu, permettrait simplement de continuer le parcours avec le label "Continuer" + icone Flèche vers la droite.
Je me débrouille après pour le contenu.

**Comment by DorineLam** [comment]
@Samuelfaure si c'est pas long de me faire ce squelette, je suis preneuse de ton aide pour que je sois autonome par la suite.

**Comment by Samuelfaure** [comment]
Ouki je peux caler ça vite fait demain je pense (ou après demain)

**Comment by DorineLam** [comment]
PR du contenu créée ici https://github.com/etalab/admin_api_entreprise/pull/678
