### ISSUE TITLE
Bug d'affichage sur l'ouverture des données

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#634]
Exemple : https://entreprise.api.gouv.fr/catalogue/dgfip/liasses_fiscales

![image](https://user-images.githubusercontent.com/5159985/182833068-c4d30508-4619-408b-be68-6d6803a39119.png)

J'ai l'impression que c'est sur toutes les pages.

Est-ce la même chose que https://github.com/etalab/admin_api_entreprise/issues/589 ? (j'ai pas l'impression)

**Comment by skelz0r** [comment]
> Est-ce la même chose que https://github.com/etalab/admin_api_entreprise/issues/589 ? (j'ai pas l'impression)

Non
