### ISSUE TITLE
Remplacer Token.renewal_url par un lien Rails

### ISSUE THREAD

**Issue by Samuelfaure** [etalab/admin_api_entreprise#652]
Cf https://github.com/etalab/admin_api_entreprise/pull/651#issuecomment-1217822279

On a un warning brakeman qu'on est obligé d'ignorer à cause de ça

**Comment by Samuelfaure** [comment]
Problème: Si on veut une route rails il faut à priori obligatoirement utiliser une redirection

 il semblerait qu'il y ait un "bug" (ou au moins un design pattern qui empêche le fonctionnement) dans Turbo qui empêche de faire une redirection depuis une turbo-frame: https://github.com/hotwired/turbo/issues/138

Y'a un draft de PR en cours pour gérer ça, et y'a des workaround avec Stimulus, mais ça semble juste pas worth it ici. Je ferme.

**Comment by skelz0r** [comment]
> Problème: Si on veut une route rails il faut à priori obligatoirement utiliser une redirection

Pourquoi ?

Je ne vois pas le rapport avec https://github.com/hotwired/turbo/issues/138 btw

Une autre approche: un helper (qui fait ~office de route). Dtf ça n'a rien à faire dans le modèle.

**Comment by Samuelfaure** [comment]
@skelz0r je suis parti du principe qu'on voulait une route de ce style:

`get 'jeton/renew', to: redirect(..datapass)`

Je vois pas comment faire différemment pour avoir une route Rails qui redirige vers un autre site?

Mais du coup je vais tenter par helper
