### ISSUE TITLE
Retour arrière depuis une fiche métier après une recherche ne fonctionne pas

### ISSUE THREAD

**Issue by skelz0r** [etalab/admin_api_entreprise#675]
Les étapes pour reproduire:

1. Aller sur https://entreprise.api.gouv.fr/catalogue
2. Taper "liasses fiscales" dans la recherche
3. Cliquer sur la fiche des liasses fiscales
4. On arrive sur https://entreprise.api.gouv.fr/catalogue/dgfip/liasses_fiscales
5. Faire retour arrière

De là on devrait voir le catalogue, la page ne change pas mais l'url change.

L'erreur js:

```js
application-69390e0216692ccb31e3bcc64724aec6077285b83ff080dd613d3151defafbd1.js:821 

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at extended._handleHit (application-69390e0216692ccb31e3bcc64724aec6077285b83ff080dd613d3151defafbd1.js:821:12)
    at application-69390e0216692ccb31e3bcc64724aec6077285b83ff080dd613d3151defafbd1.js:804:40
    at Array.forEach (<anonymous>)
    at extended._updateResults (application-69390e0216692ccb31e3bcc64724aec6077285b83ff080dd613d3151defafbd1.js:803:31)
    at application-69390e0216692ccb31e3bcc64724aec6077285b83ff080dd613d3151defafbd1.js:785:26
```

Le code:

```js
      _handleHit(controller, hit, entriesInResult) {
        var entry = document.querySelector(
          "[data-algolia-search-catalogue-hit='" + hit.objectID + "']"
        );
        entriesInResult.push(entry);

        entry
          .querySelectorAll(
            "[data-algolia-search-catalogue-hit-attribute]"
          )
```

c'est dans `app/assets/javascripts/controllers/algolia_search_catalogue_controller.js`

**Comment by Samuelfaure** [comment]
J'investigue un peu ici:

Je pense pas que l'erreur en console soit directement responsable du bug, plutôt le contraire en fait

Probablement un soucis avec turbo

**Comment by skelz0r** [comment]
> Probablement un soucis avec turbo

Pour le coup je suis quasiment sûr que c'est un souci avec notre controller js.

**Comment by skelz0r** [comment]
@Un3x ici

**Comment by skelz0r** [comment]
je précise: algolia est dans les choux là y'a moyen que ce bug ne soit pas solvable aujourd'hui.

**Comment by Un3x** [comment]
Je viens de tester sur le site, et perso ca fonctionne bien.

Pas d'erreur en js, l'url change bien, et les data filtrés sont bien mises à jour.

Éventuellement, la value de l'input n'est pas mise à jour en fonction des params de l'url, mais là c'est peut être overkill de passer du temps là dessus.

**Comment by skelz0r** [comment]
Sur Brave Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (arm64) j'ai encore le problème avec exactement mes étapes.

**Comment by Un3x** [comment]
Alors moi j'ai des comportements assez chelou dans l'ensemble mais pas ceux que tu décris.

Je viens de tester et j'ai ni erreur js en console, et le comportement de l'enchainement de ces pages me semble ok.
Par contre moi j'ai ca : 
* Aller sur https://entreprise.api.gouv.fr/catalogue
* Taper "liasses fiscales" dans la recherche
* Faire retour en arrière
* [x] Les données filtrées correspondent bien à la recherche précédente
* [x] L'url correspond bien à la recherche précédente
* [ ] Le champs input n'est pas à jour vis à vis des params de l'url
* [ ] Appuyer sur le bouton `rechercher` ne déclenche pas la recherche avec le contenu du champ

Trop bizarre, j'ai l'impression que la page filtre sur les paramètre get et la modification du champ input change les paramètres mais n'est pas initialisé avec les params (et le  bouton recherché marche pas)

**Comment by Un3x** [comment]
Okay la source du bug a été identifiée.

Il semblerait que le bug soit issue de Stimulus, plus particulièrement quand l'on revient en arrière d'une page sans Stimulus vers une page avec Stimulus.
Pour être encore plus précis, il n'est pas improbable que Turbo intervienne dedans vu que cela ne concerne pas tous les enchainements de pages. Cela se produit uniquement quand la page d'où on initie le go back est une sous url (hormis les paramètres) de la page précédentes.

Cas fonctionnel : 

* Aller sur `/catalogue`
* Faire une recherches sur `liasses fiscales`
* Cliquer sur la home qui renvoie vers `/` (ou sur le swagger, tant que la furture url ne contient pas `/catalogue`)
* Faire un retour arrière

Cas non fonctionnel : 

* Aller sur `/catalogue`
* Faire une recherches sur `liasses fiscales`
* Cliquer sur la documentation (on arrive sur `/catalogue/infogreffe/rcs/extrait`
* Faire un retour arrière

Une solution a été décrite dans une issue [github ](https://github.com/hotwired/stimulus/issues/589)

> On all non-stimulus pages that you want to enable to go Back into a stimulus-oriented page, add this script. It causes a reload only when going back into a Turbo-based page:

```
<script>
  if (window.history.state && window.history.state.turbo) {
    window.addEventListener("popstate", function () { location.reload(true); });
  }
</script>
```
Ca fonctionne, mais vraiment c'est moche niveau UX, ca cause un flickering de la page ultra crado.

**Comment by skelz0r** [comment]
imo en l'état on attend de voir ce qui se dit sur l'issue voir si un patch va sortir à un moment

**Comment by Un3x** [comment]
Okay, j'ai rajouté dans le ticket d'origine un peu de détail. 
À mon avis, ils ne corrigeront pas si on leur fournis pas un bout de code reproductible là dessus mais bon.
