### ISSUE TITLE
Fix test et page DGFIP - Liasses Fiscales

### ISSUE THREAD

**Issue by Samuelfaure** [etalab/admin_api_entreprise#679]
Cette PR https://github.com/etalab/siade/pull/270/files

A cassé cette page (et les tests) http://entreprise.api.localtest.me:3000/catalogue/dgfip/liasses_fiscales

Trois possibilités:
- On fait une ébauche de 200 Work In Progress sur le Swagger coté Siade
- On rajouter des guard clauses pour pas que ça pète dans `app/models/endpoint.rb`
- On supprime le fichier `config/endpoints/13_dgfip_liasses_fiscales.yml` temporairement

Je suis partisan de 1 ou 3

@skelz0r WDYT?

**Comment by skelz0r** [comment]
ah merde j'ai déjà corrigé @Samuelfaure :')

**Comment by skelz0r** [comment]
(j'ai ninja fix vu que j'ai eu le souci)

**Comment by skelz0r** [comment]
Closed by bf2c9629561b0e2b7f4c588c9cf27da13988d463
