### ISSUE TITLE
Filtrage des données protégées/publiques dans une url

### ISSUE THREAD

**Issue by DorineLam** [etalab/admin_api_entreprise#696]
Vu avec @Charlottecho, elle a besoin **maintenant** pour un gros acteur associatif de pouvoir envoyer une URL avec les données publiques. 

- Soit @Samuelfaure ou @skelz0r vous pouvez ajouter **d'ici la semaine prochaine** la liste déroulante qui concerne l'ouverture de la donnée. 
- Soit j'ajoute les mots clés, bricolage rapide qui aura le mérite de répondre au besoin de Charlotte sans vous déranger :)
Ce bricolage sera retiré quand on aura implémenté l'autre solution.

@Haelle je te laisse me dire ce que tu préfères.

**Comment by skelz0r** [comment]
https://v2.entreprise.api.gouv.fr/catalogue/

-> Données publique.

**Comment by skelz0r** [comment]
Ou plus simple: https://entreprise.api.gouv.fr/catalogue -> Recherche: "Données publique"

**Comment by skelz0r** [comment]
Enfin bref, y'a 0 besoin de dev là pour envoyer une liste de données publiques envoyées par API Entreprise.

**Comment by DorineLam** [comment]
@skelz0r Ce n'est pas une liste qu'il faut c'est une configuration du catalogue pour l'utilisateur spécifique que Charlotte accompagne. Et encore une fois c'est temporaire. Bon du coup je vais ajouter les mots clés.

**Comment by Haelle** [comment]
Je suis d'accord avec @skelz0r , faut voir le besoin de ce contact, mais en général c'est pas justifié... un excel suffit largement

**Comment by Haelle** [comment]
> https://v2.entreprise.api.gouv.fr/catalogue/
> 
> -> Données publique.

Pour moi c'est la meilleure solution

**Comment by Haelle** [comment]
Vu avec @DorineLam @Charlottecho , on oublie pour le moment.

Contexte : 
- s'il y a un vrai besoin usager alors faudrait plutôt un page cas d'usage OpenData (pour le moment on fait rien)
- si notre usager veut utiliser notre site pour faire des présentation autant lui filer un powerpoint...
- Si @Charlottecho en a besoin pour présenter API Entreprise à l'aide du site alors ok, et ok pour discuter de faire du tooling pour charlotte (= amélioration continue du site pour tout le monde en fait)

**Comment by skelz0r** [comment]
Le dernier point est clairement legit, si ça revient souvent on veut pouvoir avoir un truc plus propre (`Manual first`).

La page cas d'usage "OpenData" gros oui par contre ! Fondamentalement c'est une intro + le listing de toutes les entrées du catalogue qui sont open.
