### ISSUE TITLE
Email de validation Datapass non envoyé

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#699]
Il semblerait qu'on ait jamais envoyé l'email de validation de cette demande Datapass : 

- [Datapass](https://datapass.api.gouv.fr/api-entreprise/37584)
- [Mailjet](https://app.mailjet.com/contacts/overview/3hNVXX)

Ça n'a pas l'air généralisé (ou corrigé depuis), car la dernière demande validée l'email a bien été envoyé ([Mailjet](https://app.mailjet.com/contacts/overview/1IKzx3))

**Comment by skelz0r** [comment]
On a déjà eu le souci il me semble.

Manque de bol j'ai retiré le tracking ( f553cc93 ), je vais en remettre un ultra basic (DataPass id / status) histoire de debug.

Le souci ici c'est que je ne sais pas si c'est nous ou DataPass qui plante (imo c'est nous et Mailjet qui doit renvoyer un 200 avec un INTERNAL ERROR (déjà eu..))
