### ISSUE TITLE
Horaires de fonctionnement dans le fichier OpenAPI connecté à la fiche métier

### ISSUE THREAD

**Issue by DorineLam** [etalab/admin_api_entreprise#706]
### Contexte
Suite à cette PR : https://github.com/etalab/admin_api_entreprise/pull/705, les horaires de fonctionnement de l'API et le format des informations sont mis à la main dans les yml des fiches métiers des endpoints.

### To do

- **Ajouter les horaires de fonctionnement directement dans le fichier swagger** et supprimer l'info acutellement située dans les fichiers yml des endpoints et ici : https://github.com/etalab/siade/blob/develop/config/maintenances.yml#L3 
- **Connecter l'affichage sur la fiche métier directement depuis le fichier swagger**
- Répondre à la question _pourquoi format est un tableau et ne pas l'utiliser en tant que tel ?_ posée par Loïc dans la PR.

**Comment by Haelle** [comment]
@skelz0r c'est fait ça je crois ? Si oui go close

**Comment by skelz0r** [comment]
Non ce n'est pas fait.

Ça a été ajouté à la mano dans les fiches des endpoints, y'a bien une clé `x-maintenance` introduite depuis un moment ( https://github.com/etalab/siade/commit/a87a9ec9431c1b88b57e5729dca7eaacd686333e )

C'est assez facile à faire btw.
