### ISSUE TITLE
Faire un vrai logout sur api-auth

### ISSUE THREAD

**Issue by skelz0r** [etalab/admin_api_entreprise#707]
Je me rends compte que si on se logout chez nous, et qu'on se relog ça marche direct.

Faudrait logout sur api-auth

@rdubigny t'as de la doc ou une reco de ce qu'il faut faire ici ?

**Comment by rdubigny** [comment]
la doc c'est la spec open id : tu as tous les lien utile ici normalement : https://github.com/betagouv/api-auth#d%C3%A9tails-techniques

**Comment by skelz0r** [comment]
@rdubigny malheureusement la déconnexion ne m'a pas l'air spécifiée dans OpenID 1.0 (tout du moins les seules ressources que je trouve sont liées à des versions autre que la 1.0).

Je peux m'amuser à creuser le code, mais vu que c'est dispatch partout..

Y'a moyen de lister les routes ? Je ne vois rien dans https://github.com/betagouv/api-auth/blob/master/package.json#L8

Sinon .. sur DataPass ?

**Comment by skelz0r** [comment]
> Sinon .. sur DataPass ?

Bon à la lecture de https://github.com/betagouv/datapass/blob/master/backend/app/controllers/users/sessions_controller.rb#L12 je me rends compte que le signout de DataPass n'est pas un vrai logout non plus 😅

**Comment by skelz0r** [comment]
Et faut faire un ajout dans fixtures.sql pour logout_redirect_uri

**Comment by Samuelfaure** [comment]
Je tente de voir ça demain avec Raph

**Comment by skelz0r** [comment]
Je pense que c’est dans le README, si il suit la spec faut ajouter un call
http sur MCP.

**Comment by Samuelfaure** [comment]
Je m'y penche et je me rend compte que c'est relou tant qu'on a pas le full login MonComptePro (cf #816 ) à cause de edge cases avec les magic links

Beaucoup + simple d'attendre le full login avant de faire celle-ci

**Comment by skelz0r** [comment]
> Je m'y penche et je me rend compte que c'est relou tant qu'on a pas le full login MonComptePro

Dans `SessionsManagement#destroy` (au début)

```ruby
delete_on_mon_compte_pro(current_user) if current_user.from_mon_compte_pro?
```

ça me parait assez trivial

**Comment by Samuelfaure** [comment]
Bon je bloque ici, j'arrête pour le moment car ça me fait suer.

Si quelqu'un veut voir mon ébauche voir même finir, c'est sur la branche enhance/logout
