### ISSUE TITLE
Distinction éditeur <=> FS

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#715]
Le besoin est récurrent d'introduire la possibilité de distinguer un éditeur de ses clients et des FS qui ne passent pas par un éditeur.

La/les solution(s) idéales sont très coûteuses à mettre en place, je propose donc le "quick win" suivant : 

1. Introduire dans Metabase la notion de formulaire pré-rempli afin d'avoir une première grosse maille absente aujourd'hui
2. Introduire dans Metabase la notion de "Qui implémentera l'API ?"
  - [Exemple ICI](https://user-images.githubusercontent.com/5159985/193546306-3886d356-2b66-41b1-ad92-0e0de18d8688.png)

Et on accepte de les modifier nous même pour qualifier notre base et ainsi créer un décalage entre Datapass & notre backend.

En effet on ne peut pas imposer pour le moment aux usagers de remplir correctement ces champs c'est indicatif et ça ralentirai fortement les traitements Datapass...

**Comment by skelz0r** [comment]
still relevant ? sinon go close imo @Haelle
