### ISSUE TITLE
[Datapass] mails du formulaire spécifique éditeurs

### ISSUE THREAD

**Issue by DorineLam** [etalab/admin_api_entreprise#719]
Cette issue est liée à la PR suivante https://github.com/betagouv/datapass/pull/777#issuecomment-1268217820 qui ajoute un formulaire spécifique aux éditeurs.

## Objectif : 

Adapter la chaine de mails quand le formulaire pré-rempli est celui concernant les éditeurs.
Il y a peu de changement : 
On peut garder les templates de mail API Entreprise, sauf concernant le mail d'annonce de validation de la demande.
Le point de changement important est l'ajout de personnes de l'équipe en copie.

## To do : 

Si c'est un éditeur (dans le webhook 'demarches' == 'editeur'), alors:

- **Ajouter mail equipe@ en copie** des mails suivants : 
    - Mail Brouillon en attente (template 3098214)
    - Mail submit.text.erb ou Demande reçue (template 3098391)
    - Mail Demande validée à destination du demandeur (template nouveau 4254728)
- **Changement de template** pour le mail transmis au demandeur quand la demande est validée : *Nouveau Template API Entreprise** : 4254728  (toujours prendre ce template, pas de distinction sur le statut du demandeur.)
- **Ajouter dans l'objet de tous les e-mails, la mention ÉDITEUR**.
  Par exemple au lieu de : 
  > {{var:demandeur_first_name:""}} ✅ Demande validée ! Récupérez maintenant votre clé d'accès 🔑 !

  Mettre : 
  > ÉDITEUR {{Nom de l'organisation}} ✅ Demande validée ! Récupérez maintenant votre clé d'accès 🔑 !

**Comment by skelz0r** [comment]
>  Ajouter Dorine en copie cachée

Pourquoi seulement toi ? Pourquoi pas mettre une ML derrière ?

**Comment by skelz0r** [comment]
A noter que si je te mets en copie cachée ça sera dans le code, donc ton email pro sera public

**Comment by DorineLam** [comment]
Ok, on va remplacer les charlotte et dorine par du mail à equipe@.
Je vais changer dans la liste.

**Comment by skelz0r** [comment]
> C'est possible d'ajouter une variable dans l'objet d'un template qui dirait "Si c'est un formulaire éditeur alors affiche ce texte en plus" ?

Oui c'est faisable.

**Comment by skelz0r** [comment]
> Changement de template pour le mail transmis au demandeur quand la demande est validée : Nouveau Template API Entreprise* : 4254728 (toujours prendre ce template, pas de distinction sur le statut du demandeur.)

Je ne suis pas sûr de comprendre: je change pour toutes les demandes ici on est d'accord, indépendamment que ce soit un éditeur ou non ?

> Ajouter dans l'objet de tous les e-mails, la mention ÉDITEUR.

Alors là si je ne m'abuse c'est un template différent si on change le subtitle d'un email transac non ? Si c'est le cas, faut changer partout en fonction du fait que cela soit un éditeur ou non.

**Comment by DorineLam** [comment]
Dans la première partie du formulaire "L'organisation", Sous-partie :**"vous faites cette demande pour"**

**Comment by DorineLam** [comment]
> Je ne suis pas sûr de comprendre: je change pour toutes les demandes ici on est d'accord, indépendamment que ce soit un éditeur ou non

Non uniquement pour l'éditeur.

> Alors là si je ne m'abuse c'est un template différent si on change le subtitle d'un email transac non ? Si c'est le cas, faut changer partout en fonction du fait que cela soit un éditeur ou non.

Ok c'est bien ce qui me semblait ... je me demandais si il y avait un autre moyen ... Ça va être très relou à maintenir si je fais des duplicas de templates.
Du coup je propose une autre option : Le plus simple serait d'envoyer un e-mail directement à Alexis, Charlotte et équipe. Un mail séparé qui indique juste qu'il y a une nouvelle demande éditeur. 
Et un mail de fin qui indique qu'un nouvel éditeur a été habilité. C'est possible ? Ces e-mails peuvent être sans template, il faut simplement ajouter le lien de la demande et son numéro.

> Je pense que l'on a pas cette information dans les webhooks. 

Effectivement ça n'y figure pas

**Comment by skelz0r** [comment]
Ok donc le tldr:

Si c'est un éditeur (dans le webhook 'demarches' == 'editeur'), alors:

1. Changer l'email de validation pour un nouveau email 
2. Mettre equipe@ en cci sur l'ensemble des emails éditeurs
3. Ajouter une variable "editeur" dans mailjet

On est d'accord il ne manque rien ici ?

**Comment by DorineLam** [comment]
> On est d'accord il ne manque rien ici ?

En fait ce n'est pas vraiment ça : 
1. Changer l'email de validation envoyé à l'éditeur pour un nouveau email OK 👍
2. Envoyer des e-mails spécifiques, sans template, à equipe@ :

-  _Quand Mail "Brouillon en attente" est envoyé à l'éditeur_, mail envoyé à l'équipe : 
       - Objet : "ÉDITEUR - Demande en brouillon
       - Dans le corps du mail  : le lien vers la demande datapass.

- _Quand Mail "Demande reçue" est envoyé à l'éditeur_, mail envoyé à l'équipe : 
      - Objet "ÉDITEUR - Demande reçue"
      - Dans le corps du mail  : le lien vers la demande datapass.

- _Quand Mail "Demande validée" est envoyé à l'éditeur_, mail envoyé à l'équipe : 
      - Objet "ÉDITEUR - Demande validée"
      - Dans le corps du mail  : le lien vers la demande datapass.

**Comment by DorineLam** [comment]
Si c'est pas clair, on peut en parler de vive voix. Ce serait peut-être plus simple.

**Comment by skelz0r** [comment]
Oui c'est pas clair, je ne comprends pas la diff entre mettre en cci equipe@ et ce que tu proposes
