### ISSUE TITLE
Log des appels FranceConnecté

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#732]
Le CheckToken nous renvoie `client_id` et `client_name` qui doivent apparaître dans nos logs.

Aujourd'hui on log tous les appels FranceConnect avec le UID/JTI `99999999-9999-9999-9999-999999999999` comme nos jetons de tests... dur de faire la différence !

Une solution pérenne va probablement demander d'avoir un peu de recul sur l'usage, une solution court terme serait d'ajouter une colonne JSON `extra_context` qui contienne ces deux valeurs

P.S: c'est un dev conjoint siade/admin/conf logstash, mais c'est ici que le plus gros du travail sera fait...

**Comment by skelz0r** [comment]
> Aujourd'hui on log tous les appels FranceConnect avec le UID/JTI 99999999-9999-9999-9999-999999999999 comme nos jetons de tests... dur de faire la différence !

A très court terme on met autre chose pour l'un ou l'autre

**Comment by Haelle** [comment]
fermé au profit de https://github.com/etalab/siade/issues/446 et https://github.com/etalab/siade/issues/443
