### ISSUE TITLE
Cas usage num intracommunautaire

### ISSUE THREAD

**Issue by DorineLam** [etalab/admin_api_entreprise#743]
Suite à l'ajout de la nouvelle API du numéro intracommunautaire, cette issue vise à compléter les fiches cas d'usage notamment marché public :

**Comment by DorineLam** [comment]
PR ouverte ici https://github.com/etalab/admin_api_entreprise/pull/742

**Comment by Haelle** [comment]
closed by https://github.com/etalab/admin_api_entreprise/pull/754
