### ISSUE TITLE
Génération de robots.txt / sitemap.xml

### ISSUE THREAD

**Issue by skelz0r** [etalab/admin_api_entreprise#752]

**Comment by skelz0r** [comment]
@Un3x ici

**Comment by Un3x** [comment]
Question con sur le sujet : 

Ce sont des fichiers qu'il faut écrire une seule fois ou alors qu'il faut générer à la volée quand ils sont demandés.

J'imagine que le robots.txt sera plutot statique, mais le sitemap lui va évoluer.

On peut soit partir sur une tache utilisée lors de l'install et d'un deploy, ou alors d'un endpoint qui répond à l'url du fichier et qui le génère à la volée.

Faudrait savoir ce qu'on attends un peu du robots.txt et du sitemap.

J'imagine qu'il y a des urls qu'on ne souhaite pas indéxer, et des urls cannoniques qu'on va vouloir mettre en avant (pour tous les duplicats)

**Comment by skelz0r** [comment]
Je pense que dans un premier temps on peut bootstrap un truc minimaliste qui liste:

1. Les pages statiques (documentation globale) ;
2. Les endpoints
3. Les cas d'usages

Le listing exacte imo c'est du détail à ce stade.

Ici btw je pense que tu peux partir d'une gem existante (protip: en rails, il existe dans 99%+ des cas une gem qui fait ce qu'on veut) -> https://github.com/kjvarga/sitemap_generator

Donc fondamentalement c'est principalement de la config ici.

**Comment by Un3x** [comment]
Et concernant le robots.txt on sait ce qu'on veut ?

**Comment by skelz0r** [comment]
imo on allow tout ce qui est public, denied ce qui est private

**Comment by skelz0r** [comment]
private = sous authentification
