### ISSUE TITLE
Translation error pour unknown error + harden le lookup de l'erreur

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#782]
Erreur sur staging.entreprise.api.gouv.fr avec user@yopmail.com

![image](https://user-images.githubusercontent.com/5159985/203766866-ba5862e8-e9c7-4617-8b15-727e615864c0.png)

**Comment by Haelle** [comment]
ok donc le problème est temporairement résolu mais c'est pas robuste c'est ça ?

**Comment by skelz0r** [comment]
oui

**Comment by Haelle** [comment]
!later donc
