### ISSUE TITLE
Migrer vers les URL moncomptepro.beta.gouv.fr

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#783]
Migrer vers les URL https://moncomptepro.beta.gouv.fr/

**Comment by Samuelfaure** [comment]
a faire en même temps que #816

**Comment by Haelle** [comment]
`/stats` est déployé et fonctionne presque sans vue matérialisé sauf pour la dernière requête qui n'aboutit pas en moins de 30s.

De plus UptimeRobot ne peut pas servir pour mettre en cache les requêtes apparemment... Ça ne fonctionne pas

**Comment by Samuelfaure** [comment]
@Haelle Hum, est-ce que tu t'es trompé d'endroit pour ce commentaire? Ou alors il y a un lien que je ne comprend pas entre les nouvelles URL MonComptePro et `/stats` / cache ?

**Comment by skelz0r** [comment]
imo mauvais endroit
