### ISSUE TITLE
Synchroniser le blacklisting des jetons

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#787]
J'ai crée cette tâche rake : 
https://github.com/etalab/admin_api_entreprise/blob/ba62a145261a988c719d1b9915925f573794016c/lib/tasks/token.rake#L4

Mais en fait on ne peut la run que sur un seul des serveurs... si on la run sur le second serveur ça crée un nouveau jeton en fait...

Il faudrait trouver une meilleure solution.

En attendant on ne ban plus de jeton, et je supprime cette tâche rake

**Comment by Haelle** [comment]
peut être résolu avec un master/slave PG cf https://github.com/etalab/very_ansible/issues/251

**Comment by skelz0r** [comment]
Si le jeton n'existe pas sur la non-frontale, on ne fait rien.
Lors du switch on copie la db.

Il n'y a qu'à harden le script ci-dessus.

**Comment by Haelle** [comment]
je propose de mettre ce chantier en attente, si on fusionne les deux repo plus besoin de faire ce chantier

**Comment by skelz0r** [comment]
flip it, ça sera un scout commit et/ou traité lors de la fusion.
