### ISSUE TITLE
Ajouter un champ `api` aux logs

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#802]
Vous pensez que c'est une bonne idée d'ajouter un champ `api` dans les logs ? pour contenir `api_entreprise` ou `api_particulier` ?

**Comment by skelz0r** [comment]
imo oui

d'ailleurs limite on pourrait séparer en 2 tables (depuis le pipe logstash)

**Comment by skelz0r** [comment]
Je flip car ce n'est plus ici, si le besoin repop on fera le nécessaire.
