### ISSUE TITLE
Login full MonComptePro

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#816]
Aujourd'hui on a migré sur un login 100% MagicLink API Entreprise pour permettre rapidement aux contacts techniques de se connecter.

Pour des raisons d'uniformité technique entre les services de la DINUM il faudrait finaliser la migration vers un login 100% MonComptePro.

Finit les double login, les contacts métiers et techniques vont devoir avoir un compte sur MonComptePro.

Il faut donc : 
- s'assurer qu'il n'y a pas de friction dans le workflow ;
- abandonner les email génériques pour les contacts métiers/tech ;
- ?

**Comment by Haelle** [comment]
Après discussion il faut d'abord refactor notre code user/contact et n'avoir que des users

**Comment by Samuelfaure** [comment]
@Haelle À discuter avec @skelz0r du coup

**Comment by skelz0r** [comment]
C'est fini ça du coup non ?

**Comment by Samuelfaure** [comment]
@skelz0r Non non, il va falloir gérer les contacts sur MCP puis virer les magic links

**Comment by Samuelfaure** [comment]
A voir avec Alexis à son retour si on peut laisser comme ça, perso je trouve la solution actuelle pas mal du tout

**Comment by Haelle** [comment]
On abandonne les emails génériques et on suit la politique d'avoir des comptes nominatifs et donc identifié via MCP.

Il faudra donc qu'ils passent pas la moulinette MCP

**Comment by skelz0r** [comment]
Faudra penser à faire dans la foulée / en même temps les 2 issues référencés ci-dessus

**Comment by Haelle** [comment]
done
