### ISSUE TITLE
Passer par le validator W3C (HTML et CSS)

### ISSUE THREAD

**Issue by Samuelfaure** [etalab/admin_api_entreprise#837]
Cf https://github.com/etalab/admin_api_entreprise/pull/831

Faudrait corriger au minimum les problèmes en HTML

**Comment by skelz0r** [comment]
est-ce qu'on s'en fout ? :D

**Comment by Samuelfaure** [comment]
Je ferais une passe rapide cette semaine pour voir si y'a encore des quick wins, et vendredi on close pour toujours

**Comment by Samuelfaure** [comment]
Okay j'ai re-jeté un oeil, toutes les quick wins ont été faites dans la PR linkée ci-dessus, le reste c'est quasi que des trucs générés par Rails. On ferme.
