### ISSUE TITLE
Séparer les ClientIDs Particulier et Datapass

### ISSUE THREAD

**Issue by Samuelfaure** [etalab/admin_api_entreprise#839]
Cf https://github.com/etalab/admin_api_entreprise/pull/828

Raphael me fait remarquer qu'on utilise les credentials de API Entreprise pour la connection à OAuth de API Particulier.

Idéalement, nous aurions  2 différents credentials, un pour chaque app.

J'ai commencé dans la PR https://github.com/etalab/admin_api_entreprise/pull/838/files mais je me rend compte que cela complexifie énormément au niveau du code (il nous faut 2 stratégies OAuth).

Du coup je voudrais éclaircir notre stratégie: Veut-on à terme fusionner Entreprise et Particulier? Le cas échéant, pas la peine de se faire ièche avec 2 stratégies OAuth.

Veut-on garder séparés ? Dans ce cas je finis la PR.

@Haelle et @skelz0r pour opinion

**Comment by skelz0r** [comment]
Faut faire 2 stratégies pour moi.

**Comment by Haelle** [comment]
Alors oui pour faire 2 stratégies mais en quoi ça pose problème d'utiliser le même client ID ?

**Comment by Samuelfaure** [comment]
@Haelle Si on a 2 produits différents  ça fait sens d'avoir 2 authentifications différentes coté MonComptePro

Sinon la stratégie peut rester la même

**Comment by Haelle** [comment]
Est-ce que c'est vraiment deux produits ? Là c'est le backend pour récupérer les jetons pas l'API. Qu'est-ce qu'on ferait si on avait 5 ou 6 bouquets d'API dans admin ? (ce qui risque d'arriver hein)

**Comment by skelz0r** [comment]
Pour moi oui ce sont 2 produits différents, et ça fait clairement sens d'avoir 2 app oauth différenciés (et c'est trivial à étendre).

Le jour où ça vivra sur le même domaine avec les mêmes features on pourra reconsidérer la question.

**Comment by skelz0r** [comment]
On est d'accord que ça a été solved by https://github.com/etalab/admin_api_entreprise/pull/838 ?

**Comment by Samuelfaure** [comment]
C'est en prod en vrai
