### ISSUE TITLE
Augmenter le timeout dans Ferrum

### ISSUE THREAD

**Issue by Samuelfaure** [etalab/admin_api_entreprise#850]
Cf https://github.com/etalab/admin_api_entreprise/pull/838#pullrequestreview-1237566906

On a des tests qui commencent à échouer de manière random

Erreur:

```
     Ferrum::TimeoutError:
       Timed out waiting for response. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the :timeout option to a higher value might help.
```

**Comment by skelz0r** [comment]
alors non parce que le default timeout est suffisant, juste des fois ça plante dunno why, c'est pas grave

**Comment by skelz0r** [comment]
(le label "quick dev" m'a fait rire :'))

**Comment by Samuelfaure** [comment]
@skelz0r t'es sûr? ça fail régulièrement sur mon local depuis peu et en CI comme tu l'as vu sur la PR

**Comment by skelz0r** [comment]
le default est à 5, c'est une éternité
