### ISSUE TITLE
Reintroduction de token:blacklist

### ISSUE THREAD

**Issue by Samuelfaure** [etalab/admin_api_entreprise#861]
A été supprimé par https://github.com/etalab/admin_api_entreprise/commit/b240f6aa7eabc7d1d36afee568757950fb2c0cba

Réintroduit because need récemment

Fixer le soucis suivant:

```
  as it is not synchronised between servers
  it will recreate another JWT instead of a copy
  if we run it on both servers
```

Peut-être ajouter une détection pour check si on est sur la machine frontale (API OVH?) et annuler le cas échéant

@am-beta si tu as une idée de comment savoir si on est sur la frontale sans qu'on doive coder une classe entière pou request leur API (qui n'est pas la plus simple à utiliser) je suis preneur

**Comment by skelz0r** [comment]
imo go tout scripter ça dans ansible. avec un simple bash script ça se fait facile (`ssh wd "cd /var/www/admin_api_entreprise_production/current && bundle exec rake token:blacklist UUID`)

**Comment by Samuelfaure** [comment]
Je propose de ne pas toucher à ça et juste refaire le système black/whitelist quand on aura merge SIADE/Admin
