### ISSUE TITLE
Bénéficiaires effectifs dans liasses fiscales ?

### ISSUE THREAD

**Issue by DorineLam** [etalab/admin_api_entreprise#874]
Les bénéficiaires effectifs seraient dispos dans les liasses, à ajouter dans la documentation

**Comment by skelz0r** [comment]
C'est intrinsèque aux liasses en fait. Quand tu connais la fiscalité tu sais que ces données y sont (il y a ~10k données).

Cf ici: https://docs.google.com/spreadsheets/d/1iiTrXpSyWMVauNCQzKl17uPjx8FJvtaHxyr9PN4-m9o/edit#gid=99927126

Tu cherches "associé" et tu trouves des données associé aux bénéficiaires effectifs.

imo on peut juste dire que les liasses contiennent des informations sur les bénéficiaires (et tant qu'à faire énumérer d'autres infos dispo ..? je ne sais pas exactement à quoi ça sert en vrai les liasses..)

Par contre, faire une API bénéficiaires effectifs qui se basent sur les données des liasses fiscales ça peut être intéressant.

**Comment by DorineLam** [comment]
Ok super intéressant donc effectivement je vais compléter la doc.

**Comment by DorineLam** [comment]
@skelz0r le fichier excel c'est toi qui l'a exporté ou bien il est accessible en ligne ?
Sais-tu si c'est une info publique ? et donc si on pourrait le mettre à disposition des usagers ?
enfin, serait-il possible de le mettre à jour automatiquement tous les ans (car je suppose que le dico est rattaché à une année) ?

**Comment by skelz0r** [comment]
> Sais-tu si c'est une info publique ? et donc si on pourrait le mettre à disposition des usagers ?

Je pense que oui c'est une info publique vu que ce sont les informations qui sont dans les liasses fiscales remplies par les usagers (personne morale). C'est très souvent accompagnée de fiches explicatives d'ailleurs. A valider avec la DGFIP.

> enfin, serait-il possible de le mettre à jour automatiquement tous les ans (car je suppose que le dico est rattaché à une année) ?

Automatiquement non je ne pense pas. Par contre on peut demander à la DGFIP de nous consolider le fichier.

> Ce fichier est une pépite pour comprendre rapidement quelles données sont accessibles.

Fondamentalement c'est +/- documenté ici: https://www.impots.gouv.fr/formulaire/2050-liasse/liasse-fiscale-du-regime-reel-normal-en-matiere-de-bic-et-dis (j'ai cherché 10s)

Doit y avoir moyen de chopper les fiches explicatives depuis un espace sidep, voir même sur les internets si on cherche un peu plus.

De mémoire j'avais demandé ce fichier directement à la DGFIP cet été, je vais voir si dans mes emails et te fwd ça.

**Comment by DorineLam** [comment]
Merci ! Oui il y a les notices explicatives pour chaque liasse mais c'est finalement assez difficile d'obtenir un tableau général de tous les imprimés possibles, et alors de tous les imprimés + nom des champs, j'ai pas trouvé.

D'où le fait que ce tableau est assez incroyable :)

**Comment by skelz0r** [comment]
Le plus simple reste de demander à la DGFIP de nous consolider le fichier tous les ans.

Je pense qu'on peut héberger ces fichiers quelque part sur le site pour les rendre accessibles aussi.

**Comment by DorineLam** [comment]
Oui ce serait vraiment super ! En attendant, je vais faire une PR avec la possibilité de téléchargement de ce document-là. Est-ce que tu peux faire le mail à la DGFIP ou tu préfères que je m'en charge ?

**Comment by skelz0r** [comment]
T'auras peut-être des questions complémentaires en travaillant là dessus je
pense que c'est mieux que tu gères du coup.

Le mer. 18 janv. 2023 à 16:39, DorineLam ***@***.***> a
écrit :

**Comment by DorineLam** [comment]
Ça y est ! j'ai trouvé ! le document est en ligne ;) https://www.impots.gouv.fr/cahier-des-charges-edi-tdfc-0

**Comment by skelz0r** [comment]
Excellent ça!
