### ISSUE TITLE
Page de statistiques des jetons indisponible

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#893]
source ce ticket : https://support.etalab.gouv.fr/#ticket/zoom/53480

J'ai le même problème que lui sur mon compte perso.

![image](https://user-images.githubusercontent.com/5159985/216637195-65e10520-5f3e-4c95-949f-3e7233e5b0e8.png)

**Comment by skelz0r** [comment]
Oui, c'est watchdoge qui est dans les choux 🤷 => https://entreprise.api.gouv.fr/watchdoge/dashboard/current_status

**Comment by skelz0r** [comment]
@DorineLam est-ce que tu auras par hasard un screen ou des specs vis-à-vis des stats que l'on doit renvoyer ici ?

Vu qu'on n'a plus de backend pour watchdoge (là où on allait récupérer les infos) on va coller un metabase (y'a peut-être moyen de c/c l'UI et de taper sur metabase en mode API mais pas sûr à 100%, sinon ça sera l'UI metabase)

**Comment by DorineLam** [comment]
Ça peut tout à faire être l'UI métabase, ça permettra entre autres d'avoir plus de stats.
J'ai ça en maquette mais ça me semble un peu vieux, on avait retravaillé dessus : 
<img width="736" alt="Capture d’écran 2023-02-15 à 12 12 22" src="https://user-images.githubusercontent.com/46896006/219012181-7f555269-e006-4481-b999-e439a9ddd4ee.png">

**Comment by DorineLam** [comment]
Clairement, on peut créer un board sur Metabase, ce sera bien plus intéressant (si ça charge correctement)

**Comment by skelz0r** [comment]
> Clairement, on peut créer un board sur Metabase, ce sera bien plus intéressant (si ça charge correctement)

Dans tous les cas on aura des problèmes de perf que ça soit via Metabase ou via notre UI.

ça me suffit largement comme vue, je vais aller chercher des specs plus précises sur le traitement qu'on a fait pour sortir ces stats

**Comment by skelz0r** [comment]
<img width="1024" alt="Screenshot 2023-02-23 at 23 14 35" src="https://user-images.githubusercontent.com/1279968/221131460-1630fba4-7dc8-4e6d-80ef-60812256d54f.png">

https://metabase.entreprise.api.gouv.fr/question/177-backoffice-client-statistiques-dun-jeton?token_id=363d0d41-14ae-47df-bf7c-fe1e3ae5e82b&interval=24%20hours
https://metabase.entreprise.api.gouv.fr/question/178-backoffice-client-dernier-appels-dun-jeton?token_id=363d0d41-14ae-47df-bf7c-fe1e3ae5e82b&limit=10

c'est OK pour toi @DorineLam ?

**Comment by skelz0r** [comment]
C'est censé être iso avec l'ancienne implémentation modulo qu'on affiche pas si il y a 0 entrée ( un exemple avec tout https://metabase.entreprise.api.gouv.fr/question/177-backoffice-client-statistiques-dun-jeton?token_id=e484bf2b-4c10-4cae-a216-826aa4dd64c6&interval=1%20month )

**Comment by skelz0r** [comment]
T'es sûre d'avoir sauvegardé ? La question n'a pas l'air d'avoir été édité -> https://metabase.entreprise.api.gouv.fr/question/177-backoffice-client-statistiques-dun-jeton?token_id=363d0d41-14ae-47df-bf7c-fe1e3ae5e82b&interval=24%20hours

J'ai fait de manière iso à l'implémentation d'origine, mais ça me va d'affiner avec tes specs.

Si c'est OK pour toi je modifie en conséquence de ce que tu as mis dans ton commentaire.

**Comment by skelz0r** [comment]
> D'ailleurs le code 451 de la doc est obsolète, il y a plus les options non diffusible non ?

Si ce code est encore d'actu en v3, pour moi on peut le mettre dans le bleu clair (c'est du détail).

**Comment by DorineLam** [comment]
Je viens de sauvegarder, ok vas-y
