### ISSUE TITLE
Aucun jetons visibles

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#895]
Source : https://support.etalab.gouv.fr/#ticket/zoom/54019

L'utilisateur ne voit aucun jeton dans /comptes/jetons alors qu'il devrait en voir 3 selon [Metabase](https://metabase.entreprise.api.gouv.fr/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiJTRUxFQ1QgYXIuZXh0ZXJuYWxfaWQsIHQuaWQsIHQuY3JlYXRlZF9hdCwgdC5ibGFja2xpc3RlZCwgdC5hdXRob3JpemF0aW9uX3JlcXVlc3RfaWQsIGV4dHJhX2luZm9cbkZST00gdXNlcnMgdVxuTEVGVCBKT0lOIGF1dGhvcml6YXRpb25fcmVxdWVzdHMgYXIgT04gdS5pZCA9IGFyLnVzZXJfaWRcbkxFRlQgSk9JTiB0b2tlbnMgdCBPTiBhci5pZCA9IHQuYXV0aG9yaXphdGlvbl9yZXF1ZXN0X21vZGVsX2lkXG5XSEVSRSB1LmVtYWlsID0gJ2luZm9ybWF0aXF1ZUBtYWlyaWUtZGFyZGlsbHkuZnInXG5PUkRFUiBCWSBhci5leHRlcm5hbF9pZCBERVNDIiwidGVtcGxhdGUtdGFncyI6e319LCJkYXRhYmFzZSI6Mn0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==)

Un jeton a l'air étrange (3e7f427a-0804-4ca6-93f8-4624b3c853a6) car il n'a pas de `authorization_request_id`, peut-être que ça fait bugger le site ?

Vu que : 
- on a pas les logs de admin dans Metabase 
- j'ai rien vu de concluant dans Sentry
- et que je ne sais pas trop quoi chercher dans les logs Rails
je ne suis pas allé plus loin...

P.S: je continue à poster ce genre de bug en issue on est d'accord ?

**Comment by skelz0r** [comment]
@Haelle je pense que sur particulier.api.gouv.fr il verra ses jetons, mais pas sur entreprise.api.gouv.fr

est-ce que tu es sûr de ton bug report là ?

**Comment by Haelle** [comment]
c'était bien sur API Particulier en effet mais je n'ai pas relancé la personne en lui donnant le bon lien vers API Particulier.

Je close
