### ISSUE TITLE
Vérification et patch de la doc sur le lieuDeNaissance

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#906]
Les API statut étudiant et statut étudiant boursier nécessitent de fournir le `lieuDeNaissance` en paramètre.

Il semblerait que ça ne soit pas le code postal mais le code INSEE.

Il faut pour chacune des API : 

- [ ] vérifier si c'est bien le code INSEE qui est attendu ;
- [ ] vérifier si le champs est bien facultatif (et qu'on obtient quand mêmes "certains" résultats – je ne sais pas comment faire ça... à part avec des exemples limités)
- [ ] Mettre à jour le Swagger
- [ ] Mettre à jour la doc (sur api.gouv.fr ? je n'ai pas trouvé de référence à ce champ)

P.S: je n'ai pas trouvé l'endroit où on parle du fait que c'est sensé être un code postal

**Comment by Haelle** [comment]
@DorineLam c'est ici, je vais tenter de faire les deux premiers trucs avant de partir

**Comment by skelz0r** [comment]
> P.S: je n'ai pas trouvé l'endroit où on parle du fait que c'est sensé être un code postal

Il s'agit uniquement de la CAF (un `ag "codePostal"` dans le swagger te donnera la réponse). Pas impossible ici que ça soit vraiment un code postal.

Par contre pour le CNOUS et MESRI, je suis quasiment sûr qu'il s'agit du code INSEE car ces 2 APIs sont FranceConnectés, il y a d'ailleurs des 200 dans ce sens (on peut le voir sur [cette requête](https://metabase.entreprise.api.gouv.fr/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiJzZWxlY3QgXG4gICAgcm91dGUsXG4gICAgcGFyYW1zLFxuICAgIHN0YXR1cyBcbmZyb20gXG4gICAgYWNjZXNzX2xvZ3MgXG53aGVyZSBcbiAgICByb3V0ZSBpbiAoXG4gICAgICAgICdhcGlfcGFydGljdWxpZXIvdjIvY25vdXMvc3R1ZGVudF9zY2hvbGFyc2hpcCNzaG93JyxcbiAgICAgICAgJ2FwaV9wYXJ0aWN1bGllci92Mi9tZXNyaS9zdHVkZW50X3N0YXR1cyNzaG93J1xuICAgIClcbiAgIGFuZCBzdGF0dXMgPSAnMjAwJ1xuICAgYW5kIHBhcmFtcy0-PidpbmUnIGlzIG51bGwgXG4gICBhbmQgcGFyYW1zLT4-J25vbScgaXMgbnVsbCBcbmxpbWl0IDEwMCIsInRlbXBsYXRlLXRhZ3MiOnt9fSwiZGF0YWJhc2UiOjJ9LCJkaXNwbGF5IjoidGFibGUiLCJkaXNwbGF5SXNMb2NrZWQiOnRydWUsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnsidGFibGUuY29sdW1uX3dpZHRocyI6W251bGwsNDk3XX19))

**Comment by skelz0r** [comment]
PS: Ce n'est pas le bon dépôt.

**Comment by Haelle** [comment]
J'ajoute aussi que sur l'API CAF actuelle, le code postal et le code insee fonctionnent tous les deux... histoire de rendre les choses plus simples

**Comment by mazalaigue** [comment]
Seule l'API du CNOUS pose problème.
Il existe 3 endpoints pour traiter les 3 modalités.
1/ find 
2/ données-pivots
3/ INE

3 modalités 
1/ Recherche INE (pas de doute) 
2/ FranceConnect (à priori endpoint données-pivot) 
3/ Recherche par saisie des données de l'identité (a priori find)
La question est donc de s'assurer que le comportement de chaque endpoint correspond bien à notre attente

**Comment by Haelle** [comment]
Notes de la réunion d'aujourd'hui : 

- [ ] on stocke temporairement quelques exemples de paramètres d'appels
- [ ] regarder le [Swagger de l'API actuelle](https://3.basecamp.com/4318089/buckets/27091287/uploads/5264203674) avec ces fameux 2 API `find` (non FC) et `pivot` (FranceConnect)
- [ ] voir avec le CNOUS au besoin
- [ ] fixer la doc
- [ ] fixer l'API (rendre facultatif le `lieuDeNaissance`)

**Comment by skelz0r** [comment]
Tiré d'un échange de mails:

> Dans l’API StatutEtudiant de récupération du statut étudiant à partir des données d’état civil, le lieu de naissance doit contenir soit le code commune INSEE sur 5 caractères lorsque l’étudiant est né en France, soit un code pays sur 5 caractères qui correspond aux 2 caractères « 99 » auquel est concaténé les 3 caractères du code pays de la BCN (en reprenant l’exemple donné précédemment: « 99123 » pour la Russie(code BCN:« 123 »)).

**Comment by DorineLam** [comment]
Suite à cette PR, https://github.com/etalab/siade/pull/602, il s'avère que nous n'avons pas fini d'investiguer quel est le paramètre nécessaire (lieu de naissance) pour appeler le CNOUS.
https://github.com/etalab/siade/issues/610

**Comment by skelz0r** [comment]
J'ai creusé un peu et mis des infos ici: https://github.com/etalab/siade/issues/610#issuecomment-1468414966

Je suis toujours en attente des infos/données de tests du CNOUS.

**Comment by Haelle** [comment]
done
