### ISSUE TITLE
Conception simplification du renouvellement d'un jeton

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#911]
**Au T2 il s'agit juste de la conception
Au T3 on commence le dev**

L'objectif est de ne plus faire passer les usagers par Datapass quand ils veulent juste renouveler un jeton.

Ça a pleins d'implications : 
- quid des gens qui vont vouloir étendre leurs droits ?
- à partir de quand on permet de "renouveler" un jeton ?
- qui peut renouveler un jeton (automatique ou manuel ?) ?
- ...

Ces questions sont assez simples à tacler mais faut se poser et les lister pour ne rien oublier.

Il faut que ce renouvellement aille avec un renouvellement des contacts côté API Entreprise (et mise à jour Datapass ? j'aimerai bien que oui)

**Comment by skelz0r** [comment]
> L'objectif est de ne plus faire passer les usagers par Datapass

J'ai du mal à comprendre pourquoi.. surtout à la lumière des questions que tu te poses derrière: pour moi c'est exactement ce pour quoi on utilise DataPass.

En plus pour moi "Simplifier le renouvellement d'un jeton" et "ne plus faire passer les usagers par DataPass" sont 2 choses différentes et pas forcément correlée.

**Comment by Haelle** [comment]
ToDo: à mettre à jour, on se dirige plus vers une solution gérée par Datapass qui inclurait la fonctionnalité de "prolongation/renouvellement" d'un accès. Information qui nous serait transmises et on générerait un nouveau jeton

**Comment by Haelle** [comment]
Le chantier va bien être fait côté Datapass, je vais me joindre aux ateliers de conceptions qui auront lieu début mai.

Il est possible qu'on doivent faire le dev nous même, vu que Raph n'est plus vraiment sur Datapass et Isabelle bientôt en congés

### Les grandes lignes

- côté Datapass ça sera plutôt une notion de "mise à jour régulière"
- avec une notion de durée propre à chaque API
- un `revoke` automatique si aucune action de la part du FS
- possiblement deux statut sur lequel la demande bouclerait (`en cours` -> `validated` -18 mois...-> `en cours` -> `validated`)
  - et donc pour nous qu'on créerait des jetons à chaque fois que la demande arriverait en `validated` tout simplement (⚠ effets de bord en vue 🔭)

**Comment by skelz0r** [comment]
Faut introduire une notion de "bientôt révoqué" (je ne vois pas comment on peut gérer autrement sinon).

J'ai déjà conceptualisé 3 système du même style (dont 1 la semaine dernière), n'hésitez pas à venir me chercher pour la spécification fonctionnelle.

**Comment by Haelle** [comment]
invit envoyée 3 mai 11h30

**Comment by Haelle** [comment]
https://3.basecamp.com/4318089/buckets/32507002/messages/6111282362

**Comment by skelz0r** [comment]
@Haelle ça flip ça ici non ? c'est sur linear ?
