### ISSUE TITLE
[Page accueil] Bug affichage des FD 

### ISSUE THREAD

**Issue by DorineLam** [etalab/admin_api_entreprise#918]
Oups ! 
@Samuelfaure tu pourrais afficher juste "DJEPVA" et aussi réduire la taille de la typo (garder le h3 mais mettre un fr-h5) ?

![image](https://user-images.githubusercontent.com/46896006/220583575-5f6aee39-18c6-4e68-a459-a1426e47d80e.png)

**Comment by skelz0r** [comment]
C'est quelle page ?
