### ISSUE TITLE
Liste des fournisseurs sur HP: supprimer les textes (i.e. ne garder que les logos)

### ISSUE THREAD

**Issue by skelz0r** [etalab/admin_api_entreprise#920]
Je pense que ça serait plus jolie et on aurait plus le souci des noms qui dépassent ( https://github.com/etalab/admin_api_entreprise/issues/918 )

Avant:

<img width="1365" alt="Screenshot 2023-02-22 at 11 26 34" src="https://user-images.githubusercontent.com/1279968/220593698-c11716af-edf4-46f1-9860-f510261364b7.png">

Après:

<img width="1345" alt="Screenshot 2023-02-22 at 11 27 48" src="https://user-images.githubusercontent.com/1279968/220593672-bb7f5ef6-7395-47cb-ab63-224487d52931.png">

**Comment by skelz0r** [comment]
@DorineLam thoughts ?

**Comment by DorineLam** [comment]
Oui ! parfait !
