### ISSUE TITLE
Retirer les doublons en fusionnant les yml des fiches métiers

### ISSUE THREAD

**Issue by DorineLam** [etalab/admin_api_entreprise#921]
Suite à cette conversation : https://github.com/etalab/admin_api_entreprise/pull/917

Retours Loïc : 
> 
> Faut les mettre dans le même fichier (en vrai le fait d'avoir 1 ou N fichiers c'est pour qu'on se retrouve nous, le système prend tout et charge tout) et utiliser les références `&test` de ce style la:
> 
> ```yaml
> e1:
>   title: &title "Title 1"
> e2:
>   title: *title
> ```
> 
> c'est la même chose que 
> 
> ```yaml
> e1:
>   title: "Title 1"
> e2:
>   title: "Title 1"
> ```
> 
> a priori t'as plein d'exemples dans le code
> 
> Si t'as pas envie de te prendre la tête ouvre un ticket en pointant là où y'a des doublons je cleanerai.

**Comment by Haelle** [comment]
@skelz0r il y a quand même la subtilité que YAML a besoin que le `&title` existe avant son utilisation... Donc faut s'assurer que ça soit mis "avant", ça c'est un poil relou

**Comment by skelz0r** [comment]
dtf ça passera pas les tests
