### ISSUE TITLE
Magic links: undefined method `email` for nil:NilClass si le jeton est invalide

### ISSUE THREAD

**Issue by Samuelfaure** [etalab/admin_api_entreprise#933]
A voir et comprendre pourquoi

![image](https://user-images.githubusercontent.com/14159757/221610670-d5a472e1-615e-47ca-a8dc-92eae9639737.png)
Reproduction: essayer de se connecter en magic link local

(A noter, le mail n'était pas envoyé précedemment, mais suite à https://github.com/etalab/admin_api_entreprise/pull/932 le mail est bien affiché en console mais il reste une erreur en console + l'erreur en tentant de se connecter)

**Comment by skelz0r** [comment]
Le problème me semble assez obvious en lisant le code de cette classe => mettre un access token qui n'existe pas en db.

Faut faire un test de non-régression et prouver que ça ne marche pas.

**Comment by Samuelfaure** [comment]
Okay c'était un faux problème en fait: Le lien était de la forme suivante

<a href=3D"http://entreprise.api.localtest.me/compte/se-connecter/l=
ien-magique?access_token=3Da42a082c4acc01d7b14a">suivant</a>

On a probablement copié le "3D" avec l'access token. Je voudrais bien enlever ce 3D mais (ça ne semble pas possible)[https://stackoverflow.com/questions/25689375/rails-2-mailer-view-prepending-3d-to-strings]

Ça serait cool qu'on puisse faire différemment pour les mails que copier en console, que cette erreur n'arrive plus dans un moment de distraction. Si quelqu'un a une suggestion, sinon je ferme.

**Comment by skelz0r** [comment]
Je re-remet le label parce qu'il s'agit d'un vrai bug à corriger.

Si tu veux tester en local une connexion avec un magic link tu génères ça dans les seeds et tu le print en console.
