### ISSUE TITLE
[Fiche métier] Afficher différentes payload d'exemples

### ISSUE THREAD

**Issue by DorineLam** [etalab/admin_api_entreprise#935]
En utilisant le [staging](https://github.com/etalab/siade_staging_data), afficher sur la modale suivante, différents types de payload : 

<img width="898" alt="Capture d’écran 2023-02-28 à 18 24 41" src="https://user-images.githubusercontent.com/46896006/221930037-2374a96a-d981-4237-8936-2b8106e944e6.png">

Pour chaque API il s'agirait d'identifier des cas d'exemples métiers intéressants, exemple pour insee : 
- une association
- une entreprise diffusible
- une entreprise non-diffusible
- une entreprise de nouvelle-calédonie => Ce qui afficherait une erreur puisque hors périmètre.

**Comment by skelz0r** [comment]
Si tu as des real life examples pour les 4 je peux ajouter ça sur notre dépôt de payloads pour le bac à sable.

**Comment by DorineLam** [comment]
Maintenant qu'on a quelques API avec des exemples, on peut commencer à voir comme afficher cela dans la fiche métier.

J'aurai utilisé le composant [Onglets](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/onglet) du DSFR.
Concernant la donnée à afficher : 
-  les payloads sont dans siade_staging_data, [exemple ici](https://github.com/etalab/siade_staging_data/tree/develop/payloads/api_entreprise_v3_insee_etablissements). Il faut uniquement prendre celles qui ont de ce type là : `personne_morale_etat_cesse.yaml`. 
- il faudrait peut-être faire une table pour sélectionner les payloads à afficher / leur ajouter un libellé pour les onglets.

 <img width="838" alt="image" src="https://user-images.githubusercontent.com/46896006/225852380-151dca9b-f5d1-41f1-9b0e-4cab471da270.png">

**Comment by skelz0r** [comment]
Toujours dessus @Samuelfaure ? :D 

Sinon retire toi

**Comment by Samuelfaure** [comment]
J'ai give up ça ma gavé et j'ai des trucs plus urgents

**Comment by skelz0r** [comment]
C'est un poil relou car il faudrait aller cherry-pick une classe de siade pour faire ça ici, imo faut attendre la fusion des dépôts pour partager du code.

**Comment by DorineLam** [comment]
Est-ce que vous avez abandonné le sujet ... ?

**Comment by Samuelfaure** [comment]
C'est en standby jusqu'à la fusion des depôts, pour le moment c'est trop complexe pour les bénéfices imo
