### ISSUE TITLE
Intégration nouveau statut Datapass (archive - webhook)

### ISSUE THREAD

**Issue by Un3x** [etalab/admin_api_entreprise#947]
Suite aux discussions sur le ticket https://github.com/etalab/admin_api_entreprise/issues/382,

Nous avons remarqué qu'il y avait un nouvel event qui avait été intégré dans les webhook Datapass : `archive`.

Le sujet est à détailler afin de déterminer ce qu'il faut faire avec le traitement de cet event.

**Comment by skelz0r** [comment]
Ici le "archive" est un "soft delete" côté DataPass, on peut donc nous aussi appliquer un soft delete.

**Comment by Un3x** [comment]
Yes j'ai vu ca
