### ISSUE TITLE
 Intégration nouveau statut Datapass (delete - webhook)

### ISSUE THREAD

**Issue by Un3x** [etalab/admin_api_entreprise#948]
Suite aux discussions sur le ticket https://github.com/etalab/admin_api_entreprise/issues/382,

Nous avons remarqué qu'il y avait un nouvel event qui avait été intégré dans les webhook Datapass : `delete`.

Le sujet est à détailler afin de déterminer ce qu'il faut faire avec le traitement de cet event.

**Comment by skelz0r** [comment]
D'après la conversation ici: https://mattermost.incubateur.net/betagouv/pl/mkbqi8sqfinwpcqkq6qnyk6njy cet event n'est plus utilisé. imo on peut close ce ticket.
