### ISSUE TITLE
FAQ TVA enhancement

### ISSUE THREAD

**Issue by skelz0r** [etalab/admin_api_entreprise#975]
A la suite d'un email d'un FS j'ai répondu ça:

> Historiquement nous calculions le numéro de TVA à partir du numéro de siren que nous renvoyons depuis la v2. Cependant, il s'avère que cette donnée est parfois fausse pour diverses raisons (numéro de TVA étranger, pas de numéro de TVA (cas de certains micro-entreprise), cas exceptionnels où le numéro de TVA FR ne suit aucune règle etc..), c'est pourquoi nous avons introduit un nouveau service permettant de déterminer le numéro de TVA à partir d'un numéro de siren: nous générons ce numéro et vérifions auprès d'une API fournie par la commission européenne si celui-ci est valide. Si la commission européenne nous renvoie une erreur, c'est qu'à priori ce numéro n'existe pas.

A ajouter je sais pas où, mais c'est intéressant de le documenter.

**Comment by Haelle** [comment]
ping @DorineLam WDYT ?

**Comment by DorineLam** [comment]
Je ne suis pas certaine de comprendre, l'idée est de dire pourquoi on renvoie plus le num TVA en  V.3 dans les API Sirene alors qu'on l'avait en V.2 ?

**Comment by skelz0r** [comment]
Oui

**Comment by DorineLam** [comment]
On a déjà la table de correspondance ici => https://entreprise.api.gouv.fr/developpeurs/guide-migration

L'endroit logique eut été de mettre ça dans la rubrique des changements de l'API V.3 par rapport à V.2 mais là ça représente un travail énorme qu'on a pas décidé d'initier pour le passage V2 V3...
Franchement, je ne suis pas certaine de l'utilité d'ajouter plus de documentation que cette FAQ déjà présente dans la fiche métier de la TVA : https://entreprise.api.gouv.fr/catalogue/commission_europeenne/numero_tva#faq_entry_answer_0_api_entreprise_endpoint_commission_europeenne_numero_tva

**Comment by skelz0r** [comment]
Si tu juges que ce n'est pas intéressant NP.
