### ISSUE TITLE
EntrepriseWithAttestationsFacade: undefined method `code' for "attestations_agefiph":String (NoMethodError) @token_scope_codes 

### ISSUE THREAD

**Issue by skelz0r** [etalab/admin_api_entreprise#983]
A la suite de la migration des scopes, on a eu un petit oubli 

Pour le coup le classe n'est pas du tout testé, il faudrait harden ça.

Related https://errors.data.gouv.fr/organizations/sentry/issues/1354/

**Comment by Samuelfaure** [comment]
ligne [@token_scope_codes = @token.scopes.map(&:code)](https://github.com/etalab/admin_api_entreprise/blob/47ac02ad8765934054c38415c7deb5b121bc059d/app/facade/entreprise_with_attestations_facade.rb#L8-L9)

Remplacer par @token.scopes tout simplement + ajouter test non-régression
