### ISSUE TITLE
Simplifier l'utilisation du docker

### ISSUE THREAD

**Issue by Un3x** [etalab/admin_api_entreprise#989]
Afin de simplifier l'utilisation du docker, il a été proposé de créer un makefile simple permettant de réaliser l'ensemble des opérations classique lié au docker.

Parmis ces actions on pourrait avoir : 

* make start (démarrage des dockers)
* make stop (arrêt des dockers)
* make reset_database (réinitialisation de la base de données)
* make install (installation complète du projet)
* make logs (permet de consulter les derniers logs applicatif afin de les partager à d'autres personne)
* make rails (connection à l'invité de commande rails dans le container, peut servir pour du debugging)
* ...

D'autres idées ? 
@skelz0r @Samuelfaure @Haelle

**Comment by skelz0r** [comment]
imo go kiss avec les 3 premiers

y'a des binaires qui se baladent aussi pour installer and stuff, à voir si faut refactor.

**Comment by Samuelfaure** [comment]
Même avis que Loic

**Comment by Un3x** [comment]
À rajouter pour dorine : 

La génération des swaggers sur siade
