### ISSUE TITLE
Blog Post: HowTo Marché Publics avec API Entreprise

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#993]

**Comment by Charlottecho** [comment]
Suite Point avec Dorine : La page cas d'usage sur le site est suffisante car déjà utilisée et appréciée par beaucoup d'utilisateurs . Pas de besoin ici : toutes les informations jugées nécessaires sont déjà présentes sur cette page. 
A suivre ( mais pas prio donc d'ici fin 2023 ou début 2024 ) : infolettre par cas d'usage à envoyer aux users API entreprise . 

On clôture l'issue ?
