### ISSUE TITLE
Blog Post: Différence effectifs INSEE vs ACOSS/GIP-MDS

### ISSUE THREAD

**Issue by Haelle** [etalab/admin_api_entreprise#999]

**Comment by DorineLam** [comment]
@Haelle c'est noté, mais avant de faire un article de blog, il faut qu'on ait publié la V3 des effectifs, non ? Actuellement c'est pas le cas : https://entreprise.api.gouv.fr/catalogue/urssaf/effectifs

**Comment by DorineLam** [comment]
En attente d'avoir terminé l'intégration de la nouvelle API + la doc
